services:
  api-gateway:
    build:
      context: ..
      dockerfile: api-gateway/Dockerfile
    ports:
      - "8080:8080"
    environment:
      ENV: dev
      PORT: "8080"
      CUSTOMER_BFF_URL: "http://host.docker.internal:8081"
    healthcheck:
      test: [ "CMD", "wget", "-q", "-O", "-", "http://localhost:8080/healthz" ]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 5s
