// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/berberim/api/internal/analytics"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepoInterface creates a new instance of MockRepoInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepoInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepoInterface {
	mock := &MockRepoInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepoInterface is an autogenerated mock type for the RepoInterface type
type MockRepoInterface struct {
	mock.Mock
}

type MockRepoInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepoInterface) EXPECT() *MockRepoInterface_Expecter {
	return &MockRepoInterface_Expecter{mock: &_m.Mock}
}

// GetCohortActivity provides a mock function for the type MockRepoInterface
func (_mock *MockRepoInterface) GetCohortActivity(ctx context.Context, tenantID uuid.UUID, monthsBack int) ([]analytics.CohortRow, error) {
	ret := _mock.Called(ctx, tenantID, monthsBack)

	if len(ret) == 0 {
		panic("no return value specified for GetCohortActivity")
	}

	var r0 []analytics.CohortRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int) ([]analytics.CohortRow, error)); ok {
		return returnFunc(ctx, tenantID, monthsBack)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int) []analytics.CohortRow); ok {
		r0 = returnFunc(ctx, tenantID, monthsBack)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]analytics.CohortRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, int) error); ok {
		r1 = returnFunc(ctx, tenantID, monthsBack)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepoInterface_GetCohortActivity_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCohortActivity'
type MockRepoInterface_GetCohortActivity_Call struct {
	*mock.Call
}

// GetCohortActivity is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID uuid.UUID
//   - monthsBack int
func (_e *MockRepoInterface_Expecter) GetCohortActivity(ctx interface{}, tenantID interface{}, monthsBack interface{}) *MockRepoInterface_GetCohortActivity_Call {
	return &MockRepoInterface_GetCohortActivity_Call{Call: _e.mock.On("GetCohortActivity", ctx, tenantID, monthsBack)}
}

func (_c *MockRepoInterface_GetCohortActivity_Call) Run(run func(ctx context.Context, tenantID uuid.UUID, monthsBack int)) *MockRepoInterface_GetCohortActivity_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepoInterface_GetCohortActivity_Call) Return(cohortRows []analytics.CohortRow, err error) *MockRepoInterface_GetCohortActivity_Call {
	_c.Call.Return(cohortRows, err)
	return _c
}

func (_c *MockRepoInterface_GetCohortActivity_Call) RunAndReturn(run func(ctx context.Context, tenantID uuid.UUID, monthsBack int) ([]analytics.CohortRow, error)) *MockRepoInterface_GetCohortActivity_Call {
	_c.Call.Return(run)
	return _c
}

// GetCohortSizes provides a mock function for the type MockRepoInterface
func (_mock *MockRepoInterface) GetCohortSizes(ctx context.Context, tenantID uuid.UUID, monthsBack int) ([]analytics.CohortSizeRow, error) {
	ret := _mock.Called(ctx, tenantID, monthsBack)

	if len(ret) == 0 {
		panic("no return value specified for GetCohortSizes")
	}

	var r0 []analytics.CohortSizeRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int) ([]analytics.CohortSizeRow, error)); ok {
		return returnFunc(ctx, tenantID, monthsBack)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int) []analytics.CohortSizeRow); ok {
		r0 = returnFunc(ctx, tenantID, monthsBack)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]analytics.CohortSizeRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, int) error); ok {
		r1 = returnFunc(ctx, tenantID, monthsBack)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepoInterface_GetCohortSizes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCohortSizes'
type MockRepoInterface_GetCohortSizes_Call struct {
	*mock.Call
}

// GetCohortSizes is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID uuid.UUID
//   - monthsBack int
func (_e *MockRepoInterface_Expecter) GetCohortSizes(ctx interface{}, tenantID interface{}, monthsBack interface{}) *MockRepoInterface_GetCohortSizes_Call {
	return &MockRepoInterface_GetCohortSizes_Call{Call: _e.mock.On("GetCohortSizes", ctx, tenantID, monthsBack)}
}

func (_c *MockRepoInterface_GetCohortSizes_Call) Run(run func(ctx context.Context, tenantID uuid.UUID, monthsBack int)) *MockRepoInterface_GetCohortSizes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepoInterface_GetCohortSizes_Call) Return(cohortSizeRows []analytics.CohortSizeRow, err error) *MockRepoInterface_GetCohortSizes_Call {
	_c.Call.Return(cohortSizeRows, err)
	return _c
}

func (_c *MockRepoInterface_GetCohortSizes_Call) RunAndReturn(run func(ctx context.Context, tenantID uuid.UUID, monthsBack int) ([]analytics.CohortSizeRow, error)) *MockRepoInterface_GetCohortSizes_Call {
	_c.Call.Return(run)
	return _c
}

// GetLTVByAcquisitionChannel provides a mock function for the type MockRepoInterface
func (_mock *MockRepoInterface) GetLTVByAcquisitionChannel(ctx context.Context, tenantID uuid.UUID) ([]analytics.LTVSegmentRow, error) {
	ret := _mock.Called(ctx, tenantID)

	if len(ret) == 0 {
		panic("no return value specified for GetLTVByAcquisitionChannel")
	}

	var r0 []analytics.LTVSegmentRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]analytics.LTVSegmentRow, error)); ok {
		return returnFunc(ctx, tenantID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []analytics.LTVSegmentRow); ok {
		r0 = returnFunc(ctx, tenantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]analytics.LTVSegmentRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, tenantID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepoInterface_GetLTVByAcquisitionChannel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLTVByAcquisitionChannel'
type MockRepoInterface_GetLTVByAcquisitionChannel_Call struct {
	*mock.Call
}

// GetLTVByAcquisitionChannel is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID uuid.UUID
func (_e *MockRepoInterface_Expecter) GetLTVByAcquisitionChannel(ctx interface{}, tenantID interface{}) *MockRepoInterface_GetLTVByAcquisitionChannel_Call {
	return &MockRepoInterface_GetLTVByAcquisitionChannel_Call{Call: _e.mock.On("GetLTVByAcquisitionChannel", ctx, tenantID)}
}

func (_c *MockRepoInterface_GetLTVByAcquisitionChannel_Call) Run(run func(ctx context.Context, tenantID uuid.UUID)) *MockRepoInterface_GetLTVByAcquisitionChannel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepoInterface_GetLTVByAcquisitionChannel_Call) Return(lTVSegmentRows []analytics.LTVSegmentRow, err error) *MockRepoInterface_GetLTVByAcquisitionChannel_Call {
	_c.Call.Return(lTVSegmentRows, err)
	return _c
}

func (_c *MockRepoInterface_GetLTVByAcquisitionChannel_Call) RunAndReturn(run func(ctx context.Context, tenantID uuid.UUID) ([]analytics.LTVSegmentRow, error)) *MockRepoInterface_GetLTVByAcquisitionChannel_Call {
	_c.Call.Return(run)
	return _c
}

// GetLTVByCohort provides a mock function for the type MockRepoInterface
func (_mock *MockRepoInterface) GetLTVByCohort(ctx context.Context, tenantID uuid.UUID) ([]analytics.LTVSegmentRow, error) {
	ret := _mock.Called(ctx, tenantID)

	if len(ret) == 0 {
		panic("no return value specified for GetLTVByCohort")
	}

	var r0 []analytics.LTVSegmentRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]analytics.LTVSegmentRow, error)); ok {
		return returnFunc(ctx, tenantID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []analytics.LTVSegmentRow); ok {
		r0 = returnFunc(ctx, tenantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]analytics.LTVSegmentRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, tenantID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepoInterface_GetLTVByCohort_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLTVByCohort'
type MockRepoInterface_GetLTVByCohort_Call struct {
	*mock.Call
}

// GetLTVByCohort is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID uuid.UUID
func (_e *MockRepoInterface_Expecter) GetLTVByCohort(ctx interface{}, tenantID interface{}) *MockRepoInterface_GetLTVByCohort_Call {
	return &MockRepoInterface_GetLTVByCohort_Call{Call: _e.mock.On("GetLTVByCohort", ctx, tenantID)}
}

func (_c *MockRepoInterface_GetLTVByCohort_Call) Run(run func(ctx context.Context, tenantID uuid.UUID)) *MockRepoInterface_GetLTVByCohort_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepoInterface_GetLTVByCohort_Call) Return(lTVSegmentRows []analytics.LTVSegmentRow, err error) *MockRepoInterface_GetLTVByCohort_Call {
	_c.Call.Return(lTVSegmentRows, err)
	return _c
}

func (_c *MockRepoInterface_GetLTVByCohort_Call) RunAndReturn(run func(ctx context.Context, tenantID uuid.UUID) ([]analytics.LTVSegmentRow, error)) *MockRepoInterface_GetLTVByCohort_Call {
	_c.Call.Return(run)
	return _c
}

// GetLTVByServiceCategory provides a mock function for the type MockRepoInterface
func (_mock *MockRepoInterface) GetLTVByServiceCategory(ctx context.Context, tenantID uuid.UUID) ([]analytics.LTVSegmentRow, error) {
	ret := _mock.Called(ctx, tenantID)

	if len(ret) == 0 {
		panic("no return value specified for GetLTVByServiceCategory")
	}

	var r0 []analytics.LTVSegmentRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]analytics.LTVSegmentRow, error)); ok {
		return returnFunc(ctx, tenantID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []analytics.LTVSegmentRow); ok {
		r0 = returnFunc(ctx, tenantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]analytics.LTVSegmentRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, tenantID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepoInterface_GetLTVByServiceCategory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLTVByServiceCategory'
type MockRepoInterface_GetLTVByServiceCategory_Call struct {
	*mock.Call
}

// GetLTVByServiceCategory is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID uuid.UUID
func (_e *MockRepoInterface_Expecter) GetLTVByServiceCategory(ctx interface{}, tenantID interface{}) *MockRepoInterface_GetLTVByServiceCategory_Call {
	return &MockRepoInterface_GetLTVByServiceCategory_Call{Call: _e.mock.On("GetLTVByServiceCategory", ctx, tenantID)}
}

func (_c *MockRepoInterface_GetLTVByServiceCategory_Call) Run(run func(ctx context.Context, tenantID uuid.UUID)) *MockRepoInterface_GetLTVByServiceCategory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepoInterface_GetLTVByServiceCategory_Call) Return(lTVSegmentRows []analytics.LTVSegmentRow, err error) *MockRepoInterface_GetLTVByServiceCategory_Call {
	_c.Call.Return(lTVSegmentRows, err)
	return _c
}

func (_c *MockRepoInterface_GetLTVByServiceCategory_Call) RunAndReturn(run func(ctx context.Context, tenantID uuid.UUID) ([]analytics.LTVSegmentRow, error)) *MockRepoInterface_GetLTVByServiceCategory_Call {
	_c.Call.Return(run)
	return _c
}

// GetLTVSummary provides a mock function for the type MockRepoInterface
func (_mock *MockRepoInterface) GetLTVSummary(ctx context.Context, tenantID uuid.UUID) (*analytics.LTVSummaryRow, error) {
	ret := _mock.Called(ctx, tenantID)

	if len(ret) == 0 {
		panic("no return value specified for GetLTVSummary")
	}

	var r0 *analytics.LTVSummaryRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*analytics.LTVSummaryRow, error)); ok {
		return returnFunc(ctx, tenantID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *analytics.LTVSummaryRow); ok {
		r0 = returnFunc(ctx, tenantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*analytics.LTVSummaryRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, tenantID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepoInterface_GetLTVSummary_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLTVSummary'
type MockRepoInterface_GetLTVSummary_Call struct {
	*mock.Call
}

// GetLTVSummary is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID uuid.UUID
func (_e *MockRepoInterface_Expecter) GetLTVSummary(ctx interface{}, tenantID interface{}) *MockRepoInterface_GetLTVSummary_Call {
	return &MockRepoInterface_GetLTVSummary_Call{Call: _e.mock.On("GetLTVSummary", ctx, tenantID)}
}

func (_c *MockRepoInterface_GetLTVSummary_Call) Run(run func(ctx context.Context, tenantID uuid.UUID)) *MockRepoInterface_GetLTVSummary_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepoInterface_GetLTVSummary_Call) Return(lTVSummaryRow *analytics.LTVSummaryRow, err error) *MockRepoInterface_GetLTVSummary_Call {
	_c.Call.Return(lTVSummaryRow, err)
	return _c
}

func (_c *MockRepoInterface_GetLTVSummary_Call) RunAndReturn(run func(ctx context.Context, tenantID uuid.UUID) (*analytics.LTVSummaryRow, error)) *MockRepoInterface_GetLTVSummary_Call {
	_c.Call.Return(run)
	return _c
}

// GetNoShowByDayOfWeek provides a mock function for the type MockRepoInterface
func (_mock *MockRepoInterface) GetNoShowByDayOfWeek(ctx context.Context, tenantID uuid.UUID, from string, to string, tz string) ([]analytics.NoShowDayOfWeekRow, error) {
	ret := _mock.Called(ctx, tenantID, from, to, tz)

	if len(ret) == 0 {
		panic("no return value specified for GetNoShowByDayOfWeek")
	}

	var r0 []analytics.NoShowDayOfWeekRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string, string) ([]analytics.NoShowDayOfWeekRow, error)); ok {
		return returnFunc(ctx, tenantID, from, to, tz)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string, string) []analytics.NoShowDayOfWeekRow); ok {
		r0 = returnFunc(ctx, tenantID, from, to, tz)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]analytics.NoShowDayOfWeekRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, string, string) error); ok {
		r1 = returnFunc(ctx, tenantID, from, to, tz)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepoInterface_GetNoShowByDayOfWeek_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNoShowByDayOfWeek'
type MockRepoInterface_GetNoShowByDayOfWeek_Call struct {
	*mock.Call
}

// GetNoShowByDayOfWeek is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID uuid.UUID
//   - from string
//   - to string
//   - tz string
func (_e *MockRepoInterface_Expecter) GetNoShowByDayOfWeek(ctx interface{}, tenantID interface{}, from interface{}, to interface{}, tz interface{}) *MockRepoInterface_GetNoShowByDayOfWeek_Call {
	return &MockRepoInterface_GetNoShowByDayOfWeek_Call{Call: _e.mock.On("GetNoShowByDayOfWeek", ctx, tenantID, from, to, tz)}
}

func (_c *MockRepoInterface_GetNoShowByDayOfWeek_Call) Run(run func(ctx context.Context, tenantID uuid.UUID, from string, to string, tz string)) *MockRepoInterface_GetNoShowByDayOfWeek_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockRepoInterface_GetNoShowByDayOfWeek_Call) Return(noShowDayOfWeekRows []analytics.NoShowDayOfWeekRow, err error) *MockRepoInterface_GetNoShowByDayOfWeek_Call {
	_c.Call.Return(noShowDayOfWeekRows, err)
	return _c
}

func (_c *MockRepoInterface_GetNoShowByDayOfWeek_Call) RunAndReturn(run func(ctx context.Context, tenantID uuid.UUID, from string, to string, tz string) ([]analytics.NoShowDayOfWeekRow, error)) *MockRepoInterface_GetNoShowByDayOfWeek_Call {
	_c.Call.Return(run)
	return _c
}

// GetNoShowByStaff provides a mock function for the type MockRepoInterface
func (_mock *MockRepoInterface) GetNoShowByStaff(ctx context.Context, tenantID uuid.UUID, from string, to string) ([]analytics.NoShowStaffRow, error) {
	ret := _mock.Called(ctx, tenantID, from, to)

	if len(ret) == 0 {
		panic("no return value specified for GetNoShowByStaff")
	}

	var r0 []analytics.NoShowStaffRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string) ([]analytics.NoShowStaffRow, error)); ok {
		return returnFunc(ctx, tenantID, from, to)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string) []analytics.NoShowStaffRow); ok {
		r0 = returnFunc(ctx, tenantID, from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]analytics.NoShowStaffRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, string) error); ok {
		r1 = returnFunc(ctx, tenantID, from, to)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepoInterface_GetNoShowByStaff_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNoShowByStaff'
type MockRepoInterface_GetNoShowByStaff_Call struct {
	*mock.Call
}

// GetNoShowByStaff is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID uuid.UUID
//   - from string
//   - to string
func (_e *MockRepoInterface_Expecter) GetNoShowByStaff(ctx interface{}, tenantID interface{}, from interface{}, to interface{}) *MockRepoInterface_GetNoShowByStaff_Call {
	return &MockRepoInterface_GetNoShowByStaff_Call{Call: _e.mock.On("GetNoShowByStaff", ctx, tenantID, from, to)}
}

func (_c *MockRepoInterface_GetNoShowByStaff_Call) Run(run func(ctx context.Context, tenantID uuid.UUID, from string, to string)) *MockRepoInterface_GetNoShowByStaff_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRepoInterface_GetNoShowByStaff_Call) Return(noShowStaffRows []analytics.NoShowStaffRow, err error) *MockRepoInterface_GetNoShowByStaff_Call {
	_c.Call.Return(noShowStaffRows, err)
	return _c
}

func (_c *MockRepoInterface_GetNoShowByStaff_Call) RunAndReturn(run func(ctx context.Context, tenantID uuid.UUID, from string, to string) ([]analytics.NoShowStaffRow, error)) *MockRepoInterface_GetNoShowByStaff_Call {
	_c.Call.Return(run)
	return _c
}

// GetNoShowByTimeSlot provides a mock function for the type MockRepoInterface
func (_mock *MockRepoInterface) GetNoShowByTimeSlot(ctx context.Context, tenantID uuid.UUID, from string, to string, tz string) ([]analytics.NoShowTimeSlotRow, error) {
	ret := _mock.Called(ctx, tenantID, from, to, tz)

	if len(ret) == 0 {
		panic("no return value specified for GetNoShowByTimeSlot")
	}

	var r0 []analytics.NoShowTimeSlotRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string, string) ([]analytics.NoShowTimeSlotRow, error)); ok {
		return returnFunc(ctx, tenantID, from, to, tz)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string, string) []analytics.NoShowTimeSlotRow); ok {
		r0 = returnFunc(ctx, tenantID, from, to, tz)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]analytics.NoShowTimeSlotRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, string, string) error); ok {
		r1 = returnFunc(ctx, tenantID, from, to, tz)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepoInterface_GetNoShowByTimeSlot_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNoShowByTimeSlot'
type MockRepoInterface_GetNoShowByTimeSlot_Call struct {
	*mock.Call
}

// GetNoShowByTimeSlot is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID uuid.UUID
//   - from string
//   - to string
//   - tz string
func (_e *MockRepoInterface_Expecter) GetNoShowByTimeSlot(ctx interface{}, tenantID interface{}, from interface{}, to interface{}, tz interface{}) *MockRepoInterface_GetNoShowByTimeSlot_Call {
	return &MockRepoInterface_GetNoShowByTimeSlot_Call{Call: _e.mock.On("GetNoShowByTimeSlot", ctx, tenantID, from, to, tz)}
}

func (_c *MockRepoInterface_GetNoShowByTimeSlot_Call) Run(run func(ctx context.Context, tenantID uuid.UUID, from string, to string, tz string)) *MockRepoInterface_GetNoShowByTimeSlot_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockRepoInterface_GetNoShowByTimeSlot_Call) Return(noShowTimeSlotRows []analytics.NoShowTimeSlotRow, err error) *MockRepoInterface_GetNoShowByTimeSlot_Call {
	_c.Call.Return(noShowTimeSlotRows, err)
	return _c
}

func (_c *MockRepoInterface_GetNoShowByTimeSlot_Call) RunAndReturn(run func(ctx context.Context, tenantID uuid.UUID, from string, to string, tz string) ([]analytics.NoShowTimeSlotRow, error)) *MockRepoInterface_GetNoShowByTimeSlot_Call {
	_c.Call.Return(run)
	return _c
}

// GetNoShowTrends provides a mock function for the type MockRepoInterface
func (_mock *MockRepoInterface) GetNoShowTrends(ctx context.Context, tenantID uuid.UUID, from string, to string, truncUnit string) ([]analytics.NoShowTrendRow, error) {
	ret := _mock.Called(ctx, tenantID, from, to, truncUnit)

	if len(ret) == 0 {
		panic("no return value specified for GetNoShowTrends")
	}

	var r0 []analytics.NoShowTrendRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string, string) ([]analytics.NoShowTrendRow, error)); ok {
		return returnFunc(ctx, tenantID, from, to, truncUnit)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string, string, string) []analytics.NoShowTrendRow); ok {
		r0 = returnFunc(ctx, tenantID, from, to, truncUnit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]analytics.NoShowTrendRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, string, string, string) error); ok {
		r1 = returnFunc(ctx, tenantID, from, to, truncUnit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepoInterface_GetNoShowTrends_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNoShowTrends'
type MockRepoInterface_GetNoShowTrends_Call struct {
	*mock.Call
}

// GetNoShowTrends is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID uuid.UUID
//   - from string
//   - to string
//   - truncUnit string
func (_e *MockRepoInterface_Expecter) GetNoShowTrends(ctx interface{}, tenantID interface{}, from interface{}, to interface{}, truncUnit interface{}) *MockRepoInterface_GetNoShowTrends_Call {
	return &MockRepoInterface_GetNoShowTrends_Call{Call: _e.mock.On("GetNoShowTrends", ctx, tenantID, from, to, truncUnit)}
}

func (_c *MockRepoInterface_GetNoShowTrends_Call) Run(run func(ctx context.Context, tenantID uuid.UUID, from string, to string, truncUnit string)) *MockRepoInterface_GetNoShowTrends_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockRepoInterface_GetNoShowTrends_Call) Return(noShowTrendRows []analytics.NoShowTrendRow, err error) *MockRepoInterface_GetNoShowTrends_Call {
	_c.Call.Return(noShowTrendRows, err)
	return _c
}

func (_c *MockRepoInterface_GetNoShowTrends_Call) RunAndReturn(run func(ctx context.Context, tenantID uuid.UUID, from string, to string, truncUnit string) ([]analytics.NoShowTrendRow, error)) *MockRepoInterface_GetNoShowTrends_Call {
	_c.Call.Return(run)
	return _c
}

// GetRetentionBuckets provides a mock function for the type MockRepoInterface
func (_mock *MockRepoInterface) GetRetentionBuckets(ctx context.Context, tenantID uuid.UUID) ([]analytics.RetentionBucketRow, error) {
	ret := _mock.Called(ctx, tenantID)

	if len(ret) == 0 {
		panic("no return value specified for GetRetentionBuckets")
	}

	var r0 []analytics.RetentionBucketRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]analytics.RetentionBucketRow, error)); ok {
		return returnFunc(ctx, tenantID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []analytics.RetentionBucketRow); ok {
		r0 = returnFunc(ctx, tenantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]analytics.RetentionBucketRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, tenantID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepoInterface_GetRetentionBuckets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRetentionBuckets'
type MockRepoInterface_GetRetentionBuckets_Call struct {
	*mock.Call
}

// GetRetentionBuckets is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID uuid.UUID
func (_e *MockRepoInterface_Expecter) GetRetentionBuckets(ctx interface{}, tenantID interface{}) *MockRepoInterface_GetRetentionBuckets_Call {
	return &MockRepoInterface_GetRetentionBuckets_Call{Call: _e.mock.On("GetRetentionBuckets", ctx, tenantID)}
}

func (_c *MockRepoInterface_GetRetentionBuckets_Call) Run(run func(ctx context.Context, tenantID uuid.UUID)) *MockRepoInterface_GetRetentionBuckets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepoInterface_GetRetentionBuckets_Call) Return(retentionBucketRows []analytics.RetentionBucketRow, err error) *MockRepoInterface_GetRetentionBuckets_Call {
	_c.Call.Return(retentionBucketRows, err)
	return _c
}

func (_c *MockRepoInterface_GetRetentionBuckets_Call) RunAndReturn(run func(ctx context.Context, tenantID uuid.UUID) ([]analytics.RetentionBucketRow, error)) *MockRepoInterface_GetRetentionBuckets_Call {
	_c.Call.Return(run)
	return _c
}

// GetRetentionByCohort provides a mock function for the type MockRepoInterface
func (_mock *MockRepoInterface) GetRetentionByCohort(ctx context.Context, tenantID uuid.UUID, monthsBack int) ([]analytics.RetentionCohortRow, error) {
	ret := _mock.Called(ctx, tenantID, monthsBack)

	if len(ret) == 0 {
		panic("no return value specified for GetRetentionByCohort")
	}

	var r0 []analytics.RetentionCohortRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int) ([]analytics.RetentionCohortRow, error)); ok {
		return returnFunc(ctx, tenantID, monthsBack)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int) []analytics.RetentionCohortRow); ok {
		r0 = returnFunc(ctx, tenantID, monthsBack)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]analytics.RetentionCohortRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, int) error); ok {
		r1 = returnFunc(ctx, tenantID, monthsBack)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepoInterface_GetRetentionByCohort_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRetentionByCohort'
type MockRepoInterface_GetRetentionByCohort_Call struct {
	*mock.Call
}

// GetRetentionByCohort is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID uuid.UUID
//   - monthsBack int
func (_e *MockRepoInterface_Expecter) GetRetentionByCohort(ctx interface{}, tenantID interface{}, monthsBack interface{}) *MockRepoInterface_GetRetentionByCohort_Call {
	return &MockRepoInterface_GetRetentionByCohort_Call{Call: _e.mock.On("GetRetentionByCohort", ctx, tenantID, monthsBack)}
}

func (_c *MockRepoInterface_GetRetentionByCohort_Call) Run(run func(ctx context.Context, tenantID uuid.UUID, monthsBack int)) *MockRepoInterface_GetRetentionByCohort_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepoInterface_GetRetentionByCohort_Call) Return(retentionCohortRows []analytics.RetentionCohortRow, err error) *MockRepoInterface_GetRetentionByCohort_Call {
	_c.Call.Return(retentionCohortRows, err)
	return _c
}

func (_c *MockRepoInterface_GetRetentionByCohort_Call) RunAndReturn(run func(ctx context.Context, tenantID uuid.UUID, monthsBack int) ([]analytics.RetentionCohortRow, error)) *MockRepoInterface_GetRetentionByCohort_Call {
	_c.Call.Return(run)
	return _c
}

// GetRetentionSummary provides a mock function for the type MockRepoInterface
func (_mock *MockRepoInterface) GetRetentionSummary(ctx context.Context, tenantID uuid.UUID) (*analytics.RetentionSummaryRow, error) {
	ret := _mock.Called(ctx, tenantID)

	if len(ret) == 0 {
		panic("no return value specified for GetRetentionSummary")
	}

	var r0 *analytics.RetentionSummaryRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*analytics.RetentionSummaryRow, error)); ok {
		return returnFunc(ctx, tenantID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *analytics.RetentionSummaryRow); ok {
		r0 = returnFunc(ctx, tenantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*analytics.RetentionSummaryRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, tenantID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepoInterface_GetRetentionSummary_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRetentionSummary'
type MockRepoInterface_GetRetentionSummary_Call struct {
	*mock.Call
}

// GetRetentionSummary is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID uuid.UUID
func (_e *MockRepoInterface_Expecter) GetRetentionSummary(ctx interface{}, tenantID interface{}) *MockRepoInterface_GetRetentionSummary_Call {
	return &MockRepoInterface_GetRetentionSummary_Call{Call: _e.mock.On("GetRetentionSummary", ctx, tenantID)}
}

func (_c *MockRepoInterface_GetRetentionSummary_Call) Run(run func(ctx context.Context, tenantID uuid.UUID)) *MockRepoInterface_GetRetentionSummary_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepoInterface_GetRetentionSummary_Call) Return(retentionSummaryRow *analytics.RetentionSummaryRow, err error) *MockRepoInterface_GetRetentionSummary_Call {
	_c.Call.Return(retentionSummaryRow, err)
	return _c
}

func (_c *MockRepoInterface_GetRetentionSummary_Call) RunAndReturn(run func(ctx context.Context, tenantID uuid.UUID) (*analytics.RetentionSummaryRow, error)) *MockRepoInterface_GetRetentionSummary_Call {
	_c.Call.Return(run)
	return _c
}

// GetTenantTimezone provides a mock function for the type MockRepoInterface
func (_mock *MockRepoInterface) GetTenantTimezone(ctx context.Context, tenantID uuid.UUID) (string, error) {
	ret := _mock.Called(ctx, tenantID)

	if len(ret) == 0 {
		panic("no return value specified for GetTenantTimezone")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (string, error)); ok {
		return returnFunc(ctx, tenantID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) string); ok {
		r0 = returnFunc(ctx, tenantID)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, tenantID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepoInterface_GetTenantTimezone_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTenantTimezone'
type MockRepoInterface_GetTenantTimezone_Call struct {
	*mock.Call
}

// GetTenantTimezone is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID uuid.UUID
func (_e *MockRepoInterface_Expecter) GetTenantTimezone(ctx interface{}, tenantID interface{}) *MockRepoInterface_GetTenantTimezone_Call {
	return &MockRepoInterface_GetTenantTimezone_Call{Call: _e.mock.On("GetTenantTimezone", ctx, tenantID)}
}

func (_c *MockRepoInterface_GetTenantTimezone_Call) Run(run func(ctx context.Context, tenantID uuid.UUID)) *MockRepoInterface_GetTenantTimezone_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepoInterface_GetTenantTimezone_Call) Return(s string, err error) *MockRepoInterface_GetTenantTimezone_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockRepoInterface_GetTenantTimezone_Call) RunAndReturn(run func(ctx context.Context, tenantID uuid.UUID) (string, error)) *MockRepoInterface_GetTenantTimezone_Call {
	_c.Call.Return(run)
	return _c
}
