package handler

import (
	"io"
	"net/http"
	"strings"

	"github.com/berberim/api-gateway/internal/apierr"
	"github.com/berberim/api-gateway/internal/middleware"
	berberimv1 "github.com/berberim/api/api/v1"
	"github.com/labstack/echo/v5"
	"google.golang.org/grpc/metadata"
	"google.golang.org/protobuf/encoding/protojson"
	"google.golang.org/protobuf/proto"
)

var jsonUnmarshaler = protojson.UnmarshalOptions{DiscardUnknown: true}
var jsonMarshaler = protojson.MarshalOptions{EmitUnpopulated: true, UseProtoNames: true}

// Handlers is the root struct that groups all domain-specific gateway handlers.
// It is composed in server.go and its fields are registered on route groups.
type Handlers struct {
	Auth     *AuthHandler
	Public   *PublicHandler
	Customer *CustomerHandler
	Tenant   *TenantHandler
	Platform *PlatformHandler
}

// base holds the shared gRPC client and utilities used by all domain handlers.
type base struct {
	client berberimv1.BerberimAPIClient
}

// bindBody reads the request body and unmarshals JSON into msg.
func bindBody(c *echo.Context, msg proto.Message) bool {
	body, err := io.ReadAll(c.Request().Body)
	if err != nil {
		_ = apierr.Write(c, http.StatusBadRequest, apierr.New("invalid_body", "cannot read request body"))
		return false
	}
	if err := jsonUnmarshaler.Unmarshal(body, msg); err != nil {
		_ = apierr.Write(c, http.StatusBadRequest, apierr.New("invalid_body", "invalid JSON: "+err.Error()))
		return false
	}
	return true
}

// writeProto marshals a proto message to JSON and writes a 200 response.
func writeProto(c *echo.Context, msg proto.Message) error {
	b, err := jsonMarshaler.Marshal(msg)
	if err != nil {
		return apierr.Write(c, http.StatusInternalServerError, apierr.New("internal_error", "failed to marshal response"))
	}
	return c.Blob(http.StatusOK, "application/json", b)
}

// grpcErr maps a gRPC error to an HTTP JSON error response.
func grpcErr(c *echo.Context, err error) error {
	return apierr.GRPC(c, err)
}

// withAuthMeta builds outgoing gRPC metadata from the echo context.
// All identity fields come from the JWT (via AuthContext) — never from the
// request body. This is the sole place where identity is forwarded to the backend.
func withAuthMeta(c *echo.Context) metadata.MD {
	md := metadata.MD{}
	if auth, ok := middleware.AuthContextFrom(c); ok {
		md.Set("x-user-id", auth.UserID)
		md.Set("x-actor-type", auth.TokenType)
		if auth.TenantID != "" {
			md.Set("x-tenant-id", auth.TenantID)
		}
		if auth.Role != "" {
			md.Set("x-user-role", auth.Role)
		}
		if auth.SessionID != "" {
			md.Set("x-session-id", auth.SessionID)
		}
	}

	md.Set("x-request-id", resolveRequestID(c))
	if ip := c.RealIP(); ip != "" {
		md.Set("x-client-ip", ip)
	}
	if ua := c.Request().UserAgent(); ua != "" {
		md.Set("x-user-agent", ua)
	}
	copyHeaderToMeta(c, md, "X-Device-Installation-Id", "x-device-installation-id")
	copyHeaderToMeta(c, md, "X-Device-Provider", "x-device-provider")
	copyHeaderToMeta(c, md, "X-Device-Platform", "x-device-platform")
	copyHeaderToMeta(c, md, "X-App-Version", "x-app-version")
	copyHeaderToMeta(c, md, "X-Device-Locale", "x-device-locale")
	copyHeaderToMeta(c, md, "X-Device-Timezone", "x-device-timezone")
	copyHeaderToMeta(c, md, "X-Os-Version", "x-os-version")
	copyHeaderToMeta(c, md, "X-Device-Model", "x-device-model")
	copyHeaderToMeta(c, md, "X-Device-Push-Token", "x-device-push-token")

	return md
}

// resolveRequestID returns the request ID for this request.
// Prefers the client-supplied X-Request-Id header; falls back to the ID
// generated by Echo's RequestID middleware (stored on the response header).
func resolveRequestID(c *echo.Context) string {
	if rid := c.Request().Header.Get("X-Request-Id"); rid != "" {
		return rid
	}
	return c.Response().Header().Get("X-Request-Id")
}

// splitCSV splits a comma-separated query param value into a slice, filtering empty strings.
func splitCSV(s string) []string {
	if s == "" {
		return nil
	}
	parts := strings.Split(s, ",")
	out := parts[:0]
	for _, p := range parts {
		if p = strings.TrimSpace(p); p != "" {
			out = append(out, p)
		}
	}
	return out
}

func copyHeaderToMeta(c *echo.Context, md metadata.MD, headerKey, metaKey string) {
	if v := strings.TrimSpace(c.Request().Header.Get(headerKey)); v != "" {
		md.Set(metaKey, v)
	}
}
