port: "8081"
grpc_port: "9091"
http_listen_address: "0.0.0.0"
db:
  url: "postgres://postgres:postgres@localhost:5432/berberim?sslmode=disable"
jwt:
  issuer: "https://berberim.com"
  algorithm: "RS256"
  access_token_ttl: 15m
  refresh_token_ttl: 720h
  private_key_path: ""
avatar:
  max_file_size: 5242880
  upload_url_expiry: 15m
  allowed_types:
    - "image/jpeg"
    - "image/png"
    - "image/webp"
