// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"
	"time"

	"github.com/berberim/api/internal/appointment"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepoInterface creates a new instance of MockRepoInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepoInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepoInterface {
	mock := &MockRepoInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepoInterface is an autogenerated mock type for the RepoInterface type
type MockRepoInterface struct {
	mock.Mock
}

type MockRepoInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepoInterface) EXPECT() *MockRepoInterface_Expecter {
	return &MockRepoInterface_Expecter{mock: &_m.Mock}
}

// AcquireStaffScheduleLock provides a mock function for the type MockRepoInterface
func (_mock *MockRepoInterface) AcquireStaffScheduleLock(ctx context.Context, staffUserID uuid.UUID) error {
	ret := _mock.Called(ctx, staffUserID)

	if len(ret) == 0 {
		panic("no return value specified for AcquireStaffScheduleLock")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, staffUserID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepoInterface_AcquireStaffScheduleLock_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AcquireStaffScheduleLock'
type MockRepoInterface_AcquireStaffScheduleLock_Call struct {
	*mock.Call
}

// AcquireStaffScheduleLock is a helper method to define mock.On call
//   - ctx context.Context
//   - staffUserID uuid.UUID
func (_e *MockRepoInterface_Expecter) AcquireStaffScheduleLock(ctx interface{}, staffUserID interface{}) *MockRepoInterface_AcquireStaffScheduleLock_Call {
	return &MockRepoInterface_AcquireStaffScheduleLock_Call{Call: _e.mock.On("AcquireStaffScheduleLock", ctx, staffUserID)}
}

func (_c *MockRepoInterface_AcquireStaffScheduleLock_Call) Run(run func(ctx context.Context, staffUserID uuid.UUID)) *MockRepoInterface_AcquireStaffScheduleLock_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepoInterface_AcquireStaffScheduleLock_Call) Return(err error) *MockRepoInterface_AcquireStaffScheduleLock_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepoInterface_AcquireStaffScheduleLock_Call) RunAndReturn(run func(ctx context.Context, staffUserID uuid.UUID) error) *MockRepoInterface_AcquireStaffScheduleLock_Call {
	_c.Call.Return(run)
	return _c
}

// CountCustomerAppointmentsInWeek provides a mock function for the type MockRepoInterface
func (_mock *MockRepoInterface) CountCustomerAppointmentsInWeek(ctx context.Context, tenantID uuid.UUID, customerID uuid.UUID, weekStart time.Time, weekEnd time.Time) (int64, error) {
	ret := _mock.Called(ctx, tenantID, customerID, weekStart, weekEnd)

	if len(ret) == 0 {
		panic("no return value specified for CountCustomerAppointmentsInWeek")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, time.Time, time.Time) (int64, error)); ok {
		return returnFunc(ctx, tenantID, customerID, weekStart, weekEnd)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, time.Time, time.Time) int64); ok {
		r0 = returnFunc(ctx, tenantID, customerID, weekStart, weekEnd)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, time.Time, time.Time) error); ok {
		r1 = returnFunc(ctx, tenantID, customerID, weekStart, weekEnd)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepoInterface_CountCustomerAppointmentsInWeek_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountCustomerAppointmentsInWeek'
type MockRepoInterface_CountCustomerAppointmentsInWeek_Call struct {
	*mock.Call
}

// CountCustomerAppointmentsInWeek is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID uuid.UUID
//   - customerID uuid.UUID
//   - weekStart time.Time
//   - weekEnd time.Time
func (_e *MockRepoInterface_Expecter) CountCustomerAppointmentsInWeek(ctx interface{}, tenantID interface{}, customerID interface{}, weekStart interface{}, weekEnd interface{}) *MockRepoInterface_CountCustomerAppointmentsInWeek_Call {
	return &MockRepoInterface_CountCustomerAppointmentsInWeek_Call{Call: _e.mock.On("CountCustomerAppointmentsInWeek", ctx, tenantID, customerID, weekStart, weekEnd)}
}

func (_c *MockRepoInterface_CountCustomerAppointmentsInWeek_Call) Run(run func(ctx context.Context, tenantID uuid.UUID, customerID uuid.UUID, weekStart time.Time, weekEnd time.Time)) *MockRepoInterface_CountCustomerAppointmentsInWeek_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		var arg4 time.Time
		if args[4] != nil {
			arg4 = args[4].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockRepoInterface_CountCustomerAppointmentsInWeek_Call) Return(n int64, err error) *MockRepoInterface_CountCustomerAppointmentsInWeek_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockRepoInterface_CountCustomerAppointmentsInWeek_Call) RunAndReturn(run func(ctx context.Context, tenantID uuid.UUID, customerID uuid.UUID, weekStart time.Time, weekEnd time.Time) (int64, error)) *MockRepoInterface_CountCustomerAppointmentsInWeek_Call {
	_c.Call.Return(run)
	return _c
}

// CountStaffAppointmentsToday provides a mock function for the type MockRepoInterface
func (_mock *MockRepoInterface) CountStaffAppointmentsToday(ctx context.Context, tenantID uuid.UUID, staffUserID uuid.UUID, dayStart time.Time, dayEnd time.Time) (int64, error) {
	ret := _mock.Called(ctx, tenantID, staffUserID, dayStart, dayEnd)

	if len(ret) == 0 {
		panic("no return value specified for CountStaffAppointmentsToday")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, time.Time, time.Time) (int64, error)); ok {
		return returnFunc(ctx, tenantID, staffUserID, dayStart, dayEnd)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, time.Time, time.Time) int64); ok {
		r0 = returnFunc(ctx, tenantID, staffUserID, dayStart, dayEnd)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, time.Time, time.Time) error); ok {
		r1 = returnFunc(ctx, tenantID, staffUserID, dayStart, dayEnd)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepoInterface_CountStaffAppointmentsToday_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountStaffAppointmentsToday'
type MockRepoInterface_CountStaffAppointmentsToday_Call struct {
	*mock.Call
}

// CountStaffAppointmentsToday is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID uuid.UUID
//   - staffUserID uuid.UUID
//   - dayStart time.Time
//   - dayEnd time.Time
func (_e *MockRepoInterface_Expecter) CountStaffAppointmentsToday(ctx interface{}, tenantID interface{}, staffUserID interface{}, dayStart interface{}, dayEnd interface{}) *MockRepoInterface_CountStaffAppointmentsToday_Call {
	return &MockRepoInterface_CountStaffAppointmentsToday_Call{Call: _e.mock.On("CountStaffAppointmentsToday", ctx, tenantID, staffUserID, dayStart, dayEnd)}
}

func (_c *MockRepoInterface_CountStaffAppointmentsToday_Call) Run(run func(ctx context.Context, tenantID uuid.UUID, staffUserID uuid.UUID, dayStart time.Time, dayEnd time.Time)) *MockRepoInterface_CountStaffAppointmentsToday_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		var arg4 time.Time
		if args[4] != nil {
			arg4 = args[4].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockRepoInterface_CountStaffAppointmentsToday_Call) Return(n int64, err error) *MockRepoInterface_CountStaffAppointmentsToday_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockRepoInterface_CountStaffAppointmentsToday_Call) RunAndReturn(run func(ctx context.Context, tenantID uuid.UUID, staffUserID uuid.UUID, dayStart time.Time, dayEnd time.Time) (int64, error)) *MockRepoInterface_CountStaffAppointmentsToday_Call {
	_c.Call.Return(run)
	return _c
}

// CreateAppointment provides a mock function for the type MockRepoInterface
func (_mock *MockRepoInterface) CreateAppointment(ctx context.Context, a *appointment.Appointment) error {
	ret := _mock.Called(ctx, a)

	if len(ret) == 0 {
		panic("no return value specified for CreateAppointment")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *appointment.Appointment) error); ok {
		r0 = returnFunc(ctx, a)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepoInterface_CreateAppointment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAppointment'
type MockRepoInterface_CreateAppointment_Call struct {
	*mock.Call
}

// CreateAppointment is a helper method to define mock.On call
//   - ctx context.Context
//   - a *appointment.Appointment
func (_e *MockRepoInterface_Expecter) CreateAppointment(ctx interface{}, a interface{}) *MockRepoInterface_CreateAppointment_Call {
	return &MockRepoInterface_CreateAppointment_Call{Call: _e.mock.On("CreateAppointment", ctx, a)}
}

func (_c *MockRepoInterface_CreateAppointment_Call) Run(run func(ctx context.Context, a *appointment.Appointment)) *MockRepoInterface_CreateAppointment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *appointment.Appointment
		if args[1] != nil {
			arg1 = args[1].(*appointment.Appointment)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepoInterface_CreateAppointment_Call) Return(err error) *MockRepoInterface_CreateAppointment_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepoInterface_CreateAppointment_Call) RunAndReturn(run func(ctx context.Context, a *appointment.Appointment) error) *MockRepoInterface_CreateAppointment_Call {
	_c.Call.Return(run)
	return _c
}

// CreateAppointmentService provides a mock function for the type MockRepoInterface
func (_mock *MockRepoInterface) CreateAppointmentService(ctx context.Context, as *appointment.AppointmentService) error {
	ret := _mock.Called(ctx, as)

	if len(ret) == 0 {
		panic("no return value specified for CreateAppointmentService")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *appointment.AppointmentService) error); ok {
		r0 = returnFunc(ctx, as)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepoInterface_CreateAppointmentService_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAppointmentService'
type MockRepoInterface_CreateAppointmentService_Call struct {
	*mock.Call
}

// CreateAppointmentService is a helper method to define mock.On call
//   - ctx context.Context
//   - as *appointment.AppointmentService
func (_e *MockRepoInterface_Expecter) CreateAppointmentService(ctx interface{}, as interface{}) *MockRepoInterface_CreateAppointmentService_Call {
	return &MockRepoInterface_CreateAppointmentService_Call{Call: _e.mock.On("CreateAppointmentService", ctx, as)}
}

func (_c *MockRepoInterface_CreateAppointmentService_Call) Run(run func(ctx context.Context, as *appointment.AppointmentService)) *MockRepoInterface_CreateAppointmentService_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *appointment.AppointmentService
		if args[1] != nil {
			arg1 = args[1].(*appointment.AppointmentService)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepoInterface_CreateAppointmentService_Call) Return(err error) *MockRepoInterface_CreateAppointmentService_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepoInterface_CreateAppointmentService_Call) RunAndReturn(run func(ctx context.Context, as *appointment.AppointmentService) error) *MockRepoInterface_CreateAppointmentService_Call {
	_c.Call.Return(run)
	return _c
}

// GetAppointment provides a mock function for the type MockRepoInterface
func (_mock *MockRepoInterface) GetAppointment(ctx context.Context, tenantID uuid.UUID, appointmentID uuid.UUID) (*appointment.Appointment, error) {
	ret := _mock.Called(ctx, tenantID, appointmentID)

	if len(ret) == 0 {
		panic("no return value specified for GetAppointment")
	}

	var r0 *appointment.Appointment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*appointment.Appointment, error)); ok {
		return returnFunc(ctx, tenantID, appointmentID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *appointment.Appointment); ok {
		r0 = returnFunc(ctx, tenantID, appointmentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*appointment.Appointment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, tenantID, appointmentID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepoInterface_GetAppointment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAppointment'
type MockRepoInterface_GetAppointment_Call struct {
	*mock.Call
}

// GetAppointment is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID uuid.UUID
//   - appointmentID uuid.UUID
func (_e *MockRepoInterface_Expecter) GetAppointment(ctx interface{}, tenantID interface{}, appointmentID interface{}) *MockRepoInterface_GetAppointment_Call {
	return &MockRepoInterface_GetAppointment_Call{Call: _e.mock.On("GetAppointment", ctx, tenantID, appointmentID)}
}

func (_c *MockRepoInterface_GetAppointment_Call) Run(run func(ctx context.Context, tenantID uuid.UUID, appointmentID uuid.UUID)) *MockRepoInterface_GetAppointment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepoInterface_GetAppointment_Call) Return(appointment1 *appointment.Appointment, err error) *MockRepoInterface_GetAppointment_Call {
	_c.Call.Return(appointment1, err)
	return _c
}

func (_c *MockRepoInterface_GetAppointment_Call) RunAndReturn(run func(ctx context.Context, tenantID uuid.UUID, appointmentID uuid.UUID) (*appointment.Appointment, error)) *MockRepoInterface_GetAppointment_Call {
	_c.Call.Return(run)
	return _c
}

// GetAppointmentByIdempotencyKey provides a mock function for the type MockRepoInterface
func (_mock *MockRepoInterface) GetAppointmentByIdempotencyKey(ctx context.Context, tenantID uuid.UUID, key string) (*appointment.Appointment, error) {
	ret := _mock.Called(ctx, tenantID, key)

	if len(ret) == 0 {
		panic("no return value specified for GetAppointmentByIdempotencyKey")
	}

	var r0 *appointment.Appointment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) (*appointment.Appointment, error)); ok {
		return returnFunc(ctx, tenantID, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) *appointment.Appointment); ok {
		r0 = returnFunc(ctx, tenantID, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*appointment.Appointment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = returnFunc(ctx, tenantID, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepoInterface_GetAppointmentByIdempotencyKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAppointmentByIdempotencyKey'
type MockRepoInterface_GetAppointmentByIdempotencyKey_Call struct {
	*mock.Call
}

// GetAppointmentByIdempotencyKey is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID uuid.UUID
//   - key string
func (_e *MockRepoInterface_Expecter) GetAppointmentByIdempotencyKey(ctx interface{}, tenantID interface{}, key interface{}) *MockRepoInterface_GetAppointmentByIdempotencyKey_Call {
	return &MockRepoInterface_GetAppointmentByIdempotencyKey_Call{Call: _e.mock.On("GetAppointmentByIdempotencyKey", ctx, tenantID, key)}
}

func (_c *MockRepoInterface_GetAppointmentByIdempotencyKey_Call) Run(run func(ctx context.Context, tenantID uuid.UUID, key string)) *MockRepoInterface_GetAppointmentByIdempotencyKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepoInterface_GetAppointmentByIdempotencyKey_Call) Return(appointment1 *appointment.Appointment, err error) *MockRepoInterface_GetAppointmentByIdempotencyKey_Call {
	_c.Call.Return(appointment1, err)
	return _c
}

func (_c *MockRepoInterface_GetAppointmentByIdempotencyKey_Call) RunAndReturn(run func(ctx context.Context, tenantID uuid.UUID, key string) (*appointment.Appointment, error)) *MockRepoInterface_GetAppointmentByIdempotencyKey_Call {
	_c.Call.Return(run)
	return _c
}

// GetAppointmentForUpdate provides a mock function for the type MockRepoInterface
func (_mock *MockRepoInterface) GetAppointmentForUpdate(ctx context.Context, tenantID uuid.UUID, appointmentID uuid.UUID) (*appointment.Appointment, error) {
	ret := _mock.Called(ctx, tenantID, appointmentID)

	if len(ret) == 0 {
		panic("no return value specified for GetAppointmentForUpdate")
	}

	var r0 *appointment.Appointment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*appointment.Appointment, error)); ok {
		return returnFunc(ctx, tenantID, appointmentID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *appointment.Appointment); ok {
		r0 = returnFunc(ctx, tenantID, appointmentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*appointment.Appointment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, tenantID, appointmentID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepoInterface_GetAppointmentForUpdate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAppointmentForUpdate'
type MockRepoInterface_GetAppointmentForUpdate_Call struct {
	*mock.Call
}

// GetAppointmentForUpdate is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID uuid.UUID
//   - appointmentID uuid.UUID
func (_e *MockRepoInterface_Expecter) GetAppointmentForUpdate(ctx interface{}, tenantID interface{}, appointmentID interface{}) *MockRepoInterface_GetAppointmentForUpdate_Call {
	return &MockRepoInterface_GetAppointmentForUpdate_Call{Call: _e.mock.On("GetAppointmentForUpdate", ctx, tenantID, appointmentID)}
}

func (_c *MockRepoInterface_GetAppointmentForUpdate_Call) Run(run func(ctx context.Context, tenantID uuid.UUID, appointmentID uuid.UUID)) *MockRepoInterface_GetAppointmentForUpdate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepoInterface_GetAppointmentForUpdate_Call) Return(appointment1 *appointment.Appointment, err error) *MockRepoInterface_GetAppointmentForUpdate_Call {
	_c.Call.Return(appointment1, err)
	return _c
}

func (_c *MockRepoInterface_GetAppointmentForUpdate_Call) RunAndReturn(run func(ctx context.Context, tenantID uuid.UUID, appointmentID uuid.UUID) (*appointment.Appointment, error)) *MockRepoInterface_GetAppointmentForUpdate_Call {
	_c.Call.Return(run)
	return _c
}

// GetCustomerBookingPatterns provides a mock function for the type MockRepoInterface
func (_mock *MockRepoInterface) GetCustomerBookingPatterns(ctx context.Context, tenantID uuid.UUID, customerID uuid.UUID, tz string) (*appointment.BookingPattern, error) {
	ret := _mock.Called(ctx, tenantID, customerID, tz)

	if len(ret) == 0 {
		panic("no return value specified for GetCustomerBookingPatterns")
	}

	var r0 *appointment.BookingPattern
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string) (*appointment.BookingPattern, error)); ok {
		return returnFunc(ctx, tenantID, customerID, tz)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string) *appointment.BookingPattern); ok {
		r0 = returnFunc(ctx, tenantID, customerID, tz)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*appointment.BookingPattern)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, string) error); ok {
		r1 = returnFunc(ctx, tenantID, customerID, tz)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepoInterface_GetCustomerBookingPatterns_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCustomerBookingPatterns'
type MockRepoInterface_GetCustomerBookingPatterns_Call struct {
	*mock.Call
}

// GetCustomerBookingPatterns is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID uuid.UUID
//   - customerID uuid.UUID
//   - tz string
func (_e *MockRepoInterface_Expecter) GetCustomerBookingPatterns(ctx interface{}, tenantID interface{}, customerID interface{}, tz interface{}) *MockRepoInterface_GetCustomerBookingPatterns_Call {
	return &MockRepoInterface_GetCustomerBookingPatterns_Call{Call: _e.mock.On("GetCustomerBookingPatterns", ctx, tenantID, customerID, tz)}
}

func (_c *MockRepoInterface_GetCustomerBookingPatterns_Call) Run(run func(ctx context.Context, tenantID uuid.UUID, customerID uuid.UUID, tz string)) *MockRepoInterface_GetCustomerBookingPatterns_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRepoInterface_GetCustomerBookingPatterns_Call) Return(bookingPattern *appointment.BookingPattern, err error) *MockRepoInterface_GetCustomerBookingPatterns_Call {
	_c.Call.Return(bookingPattern, err)
	return _c
}

func (_c *MockRepoInterface_GetCustomerBookingPatterns_Call) RunAndReturn(run func(ctx context.Context, tenantID uuid.UUID, customerID uuid.UUID, tz string) (*appointment.BookingPattern, error)) *MockRepoInterface_GetCustomerBookingPatterns_Call {
	_c.Call.Return(run)
	return _c
}

// GetCustomerInfo provides a mock function for the type MockRepoInterface
func (_mock *MockRepoInterface) GetCustomerInfo(ctx context.Context, tenantID uuid.UUID, customerID uuid.UUID) (*appointment.CustomerInfo, error) {
	ret := _mock.Called(ctx, tenantID, customerID)

	if len(ret) == 0 {
		panic("no return value specified for GetCustomerInfo")
	}

	var r0 *appointment.CustomerInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*appointment.CustomerInfo, error)); ok {
		return returnFunc(ctx, tenantID, customerID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *appointment.CustomerInfo); ok {
		r0 = returnFunc(ctx, tenantID, customerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*appointment.CustomerInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, tenantID, customerID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepoInterface_GetCustomerInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCustomerInfo'
type MockRepoInterface_GetCustomerInfo_Call struct {
	*mock.Call
}

// GetCustomerInfo is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID uuid.UUID
//   - customerID uuid.UUID
func (_e *MockRepoInterface_Expecter) GetCustomerInfo(ctx interface{}, tenantID interface{}, customerID interface{}) *MockRepoInterface_GetCustomerInfo_Call {
	return &MockRepoInterface_GetCustomerInfo_Call{Call: _e.mock.On("GetCustomerInfo", ctx, tenantID, customerID)}
}

func (_c *MockRepoInterface_GetCustomerInfo_Call) Run(run func(ctx context.Context, tenantID uuid.UUID, customerID uuid.UUID)) *MockRepoInterface_GetCustomerInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepoInterface_GetCustomerInfo_Call) Return(customerInfo *appointment.CustomerInfo, err error) *MockRepoInterface_GetCustomerInfo_Call {
	_c.Call.Return(customerInfo, err)
	return _c
}

func (_c *MockRepoInterface_GetCustomerInfo_Call) RunAndReturn(run func(ctx context.Context, tenantID uuid.UUID, customerID uuid.UUID) (*appointment.CustomerInfo, error)) *MockRepoInterface_GetCustomerInfo_Call {
	_c.Call.Return(run)
	return _c
}

// GetMaxWeeklyCustomerBookings provides a mock function for the type MockRepoInterface
func (_mock *MockRepoInterface) GetMaxWeeklyCustomerBookings(ctx context.Context, tenantID uuid.UUID) (int, error) {
	ret := _mock.Called(ctx, tenantID)

	if len(ret) == 0 {
		panic("no return value specified for GetMaxWeeklyCustomerBookings")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (int, error)); ok {
		return returnFunc(ctx, tenantID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) int); ok {
		r0 = returnFunc(ctx, tenantID)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, tenantID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepoInterface_GetMaxWeeklyCustomerBookings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMaxWeeklyCustomerBookings'
type MockRepoInterface_GetMaxWeeklyCustomerBookings_Call struct {
	*mock.Call
}

// GetMaxWeeklyCustomerBookings is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID uuid.UUID
func (_e *MockRepoInterface_Expecter) GetMaxWeeklyCustomerBookings(ctx interface{}, tenantID interface{}) *MockRepoInterface_GetMaxWeeklyCustomerBookings_Call {
	return &MockRepoInterface_GetMaxWeeklyCustomerBookings_Call{Call: _e.mock.On("GetMaxWeeklyCustomerBookings", ctx, tenantID)}
}

func (_c *MockRepoInterface_GetMaxWeeklyCustomerBookings_Call) Run(run func(ctx context.Context, tenantID uuid.UUID)) *MockRepoInterface_GetMaxWeeklyCustomerBookings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepoInterface_GetMaxWeeklyCustomerBookings_Call) Return(n int, err error) *MockRepoInterface_GetMaxWeeklyCustomerBookings_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockRepoInterface_GetMaxWeeklyCustomerBookings_Call) RunAndReturn(run func(ctx context.Context, tenantID uuid.UUID) (int, error)) *MockRepoInterface_GetMaxWeeklyCustomerBookings_Call {
	_c.Call.Return(run)
	return _c
}

// GetServiceByID provides a mock function for the type MockRepoInterface
func (_mock *MockRepoInterface) GetServiceByID(ctx context.Context, tenantID uuid.UUID, serviceID uuid.UUID) (*appointment.ServiceRecord, error) {
	ret := _mock.Called(ctx, tenantID, serviceID)

	if len(ret) == 0 {
		panic("no return value specified for GetServiceByID")
	}

	var r0 *appointment.ServiceRecord
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*appointment.ServiceRecord, error)); ok {
		return returnFunc(ctx, tenantID, serviceID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *appointment.ServiceRecord); ok {
		r0 = returnFunc(ctx, tenantID, serviceID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*appointment.ServiceRecord)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, tenantID, serviceID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepoInterface_GetServiceByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetServiceByID'
type MockRepoInterface_GetServiceByID_Call struct {
	*mock.Call
}

// GetServiceByID is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID uuid.UUID
//   - serviceID uuid.UUID
func (_e *MockRepoInterface_Expecter) GetServiceByID(ctx interface{}, tenantID interface{}, serviceID interface{}) *MockRepoInterface_GetServiceByID_Call {
	return &MockRepoInterface_GetServiceByID_Call{Call: _e.mock.On("GetServiceByID", ctx, tenantID, serviceID)}
}

func (_c *MockRepoInterface_GetServiceByID_Call) Run(run func(ctx context.Context, tenantID uuid.UUID, serviceID uuid.UUID)) *MockRepoInterface_GetServiceByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepoInterface_GetServiceByID_Call) Return(serviceRecord *appointment.ServiceRecord, err error) *MockRepoInterface_GetServiceByID_Call {
	_c.Call.Return(serviceRecord, err)
	return _c
}

func (_c *MockRepoInterface_GetServiceByID_Call) RunAndReturn(run func(ctx context.Context, tenantID uuid.UUID, serviceID uuid.UUID) (*appointment.ServiceRecord, error)) *MockRepoInterface_GetServiceByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetStaffCustomPrice provides a mock function for the type MockRepoInterface
func (_mock *MockRepoInterface) GetStaffCustomPrice(ctx context.Context, staffUserID uuid.UUID, serviceID uuid.UUID) (string, error) {
	ret := _mock.Called(ctx, staffUserID, serviceID)

	if len(ret) == 0 {
		panic("no return value specified for GetStaffCustomPrice")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (string, error)); ok {
		return returnFunc(ctx, staffUserID, serviceID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) string); ok {
		r0 = returnFunc(ctx, staffUserID, serviceID)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, staffUserID, serviceID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepoInterface_GetStaffCustomPrice_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStaffCustomPrice'
type MockRepoInterface_GetStaffCustomPrice_Call struct {
	*mock.Call
}

// GetStaffCustomPrice is a helper method to define mock.On call
//   - ctx context.Context
//   - staffUserID uuid.UUID
//   - serviceID uuid.UUID
func (_e *MockRepoInterface_Expecter) GetStaffCustomPrice(ctx interface{}, staffUserID interface{}, serviceID interface{}) *MockRepoInterface_GetStaffCustomPrice_Call {
	return &MockRepoInterface_GetStaffCustomPrice_Call{Call: _e.mock.On("GetStaffCustomPrice", ctx, staffUserID, serviceID)}
}

func (_c *MockRepoInterface_GetStaffCustomPrice_Call) Run(run func(ctx context.Context, staffUserID uuid.UUID, serviceID uuid.UUID)) *MockRepoInterface_GetStaffCustomPrice_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepoInterface_GetStaffCustomPrice_Call) Return(s string, err error) *MockRepoInterface_GetStaffCustomPrice_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockRepoInterface_GetStaffCustomPrice_Call) RunAndReturn(run func(ctx context.Context, staffUserID uuid.UUID, serviceID uuid.UUID) (string, error)) *MockRepoInterface_GetStaffCustomPrice_Call {
	_c.Call.Return(run)
	return _c
}

// GetStaffMember provides a mock function for the type MockRepoInterface
func (_mock *MockRepoInterface) GetStaffMember(ctx context.Context, tenantID uuid.UUID, staffUserID uuid.UUID) (*appointment.StaffMember, error) {
	ret := _mock.Called(ctx, tenantID, staffUserID)

	if len(ret) == 0 {
		panic("no return value specified for GetStaffMember")
	}

	var r0 *appointment.StaffMember
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*appointment.StaffMember, error)); ok {
		return returnFunc(ctx, tenantID, staffUserID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *appointment.StaffMember); ok {
		r0 = returnFunc(ctx, tenantID, staffUserID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*appointment.StaffMember)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, tenantID, staffUserID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepoInterface_GetStaffMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStaffMember'
type MockRepoInterface_GetStaffMember_Call struct {
	*mock.Call
}

// GetStaffMember is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID uuid.UUID
//   - staffUserID uuid.UUID
func (_e *MockRepoInterface_Expecter) GetStaffMember(ctx interface{}, tenantID interface{}, staffUserID interface{}) *MockRepoInterface_GetStaffMember_Call {
	return &MockRepoInterface_GetStaffMember_Call{Call: _e.mock.On("GetStaffMember", ctx, tenantID, staffUserID)}
}

func (_c *MockRepoInterface_GetStaffMember_Call) Run(run func(ctx context.Context, tenantID uuid.UUID, staffUserID uuid.UUID)) *MockRepoInterface_GetStaffMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepoInterface_GetStaffMember_Call) Return(staffMember *appointment.StaffMember, err error) *MockRepoInterface_GetStaffMember_Call {
	_c.Call.Return(staffMember, err)
	return _c
}

func (_c *MockRepoInterface_GetStaffMember_Call) RunAndReturn(run func(ctx context.Context, tenantID uuid.UUID, staffUserID uuid.UUID) (*appointment.StaffMember, error)) *MockRepoInterface_GetStaffMember_Call {
	_c.Call.Return(run)
	return _c
}

// GetTenantBookingConfig provides a mock function for the type MockRepoInterface
func (_mock *MockRepoInterface) GetTenantBookingConfig(ctx context.Context, tenantID uuid.UUID) (*appointment.TenantBookingConfig, error) {
	ret := _mock.Called(ctx, tenantID)

	if len(ret) == 0 {
		panic("no return value specified for GetTenantBookingConfig")
	}

	var r0 *appointment.TenantBookingConfig
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*appointment.TenantBookingConfig, error)); ok {
		return returnFunc(ctx, tenantID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) *appointment.TenantBookingConfig); ok {
		r0 = returnFunc(ctx, tenantID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*appointment.TenantBookingConfig)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, tenantID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepoInterface_GetTenantBookingConfig_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTenantBookingConfig'
type MockRepoInterface_GetTenantBookingConfig_Call struct {
	*mock.Call
}

// GetTenantBookingConfig is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID uuid.UUID
func (_e *MockRepoInterface_Expecter) GetTenantBookingConfig(ctx interface{}, tenantID interface{}) *MockRepoInterface_GetTenantBookingConfig_Call {
	return &MockRepoInterface_GetTenantBookingConfig_Call{Call: _e.mock.On("GetTenantBookingConfig", ctx, tenantID)}
}

func (_c *MockRepoInterface_GetTenantBookingConfig_Call) Run(run func(ctx context.Context, tenantID uuid.UUID)) *MockRepoInterface_GetTenantBookingConfig_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepoInterface_GetTenantBookingConfig_Call) Return(tenantBookingConfig *appointment.TenantBookingConfig, err error) *MockRepoInterface_GetTenantBookingConfig_Call {
	_c.Call.Return(tenantBookingConfig, err)
	return _c
}

func (_c *MockRepoInterface_GetTenantBookingConfig_Call) RunAndReturn(run func(ctx context.Context, tenantID uuid.UUID) (*appointment.TenantBookingConfig, error)) *MockRepoInterface_GetTenantBookingConfig_Call {
	_c.Call.Return(run)
	return _c
}

// GetTenantPopularHours provides a mock function for the type MockRepoInterface
func (_mock *MockRepoInterface) GetTenantPopularHours(ctx context.Context, tenantID uuid.UUID, tz string) ([]appointment.PopularHour, error) {
	ret := _mock.Called(ctx, tenantID, tz)

	if len(ret) == 0 {
		panic("no return value specified for GetTenantPopularHours")
	}

	var r0 []appointment.PopularHour
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) ([]appointment.PopularHour, error)); ok {
		return returnFunc(ctx, tenantID, tz)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, string) []appointment.PopularHour); ok {
		r0 = returnFunc(ctx, tenantID, tz)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]appointment.PopularHour)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, string) error); ok {
		r1 = returnFunc(ctx, tenantID, tz)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepoInterface_GetTenantPopularHours_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTenantPopularHours'
type MockRepoInterface_GetTenantPopularHours_Call struct {
	*mock.Call
}

// GetTenantPopularHours is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID uuid.UUID
//   - tz string
func (_e *MockRepoInterface_Expecter) GetTenantPopularHours(ctx interface{}, tenantID interface{}, tz interface{}) *MockRepoInterface_GetTenantPopularHours_Call {
	return &MockRepoInterface_GetTenantPopularHours_Call{Call: _e.mock.On("GetTenantPopularHours", ctx, tenantID, tz)}
}

func (_c *MockRepoInterface_GetTenantPopularHours_Call) Run(run func(ctx context.Context, tenantID uuid.UUID, tz string)) *MockRepoInterface_GetTenantPopularHours_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepoInterface_GetTenantPopularHours_Call) Return(popularHours []appointment.PopularHour, err error) *MockRepoInterface_GetTenantPopularHours_Call {
	_c.Call.Return(popularHours, err)
	return _c
}

func (_c *MockRepoInterface_GetTenantPopularHours_Call) RunAndReturn(run func(ctx context.Context, tenantID uuid.UUID, tz string) ([]appointment.PopularHour, error)) *MockRepoInterface_GetTenantPopularHours_Call {
	_c.Call.Return(run)
	return _c
}

// GetTenantTimezone provides a mock function for the type MockRepoInterface
func (_mock *MockRepoInterface) GetTenantTimezone(ctx context.Context, tenantID uuid.UUID) (string, error) {
	ret := _mock.Called(ctx, tenantID)

	if len(ret) == 0 {
		panic("no return value specified for GetTenantTimezone")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (string, error)); ok {
		return returnFunc(ctx, tenantID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) string); ok {
		r0 = returnFunc(ctx, tenantID)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, tenantID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepoInterface_GetTenantTimezone_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTenantTimezone'
type MockRepoInterface_GetTenantTimezone_Call struct {
	*mock.Call
}

// GetTenantTimezone is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID uuid.UUID
func (_e *MockRepoInterface_Expecter) GetTenantTimezone(ctx interface{}, tenantID interface{}) *MockRepoInterface_GetTenantTimezone_Call {
	return &MockRepoInterface_GetTenantTimezone_Call{Call: _e.mock.On("GetTenantTimezone", ctx, tenantID)}
}

func (_c *MockRepoInterface_GetTenantTimezone_Call) Run(run func(ctx context.Context, tenantID uuid.UUID)) *MockRepoInterface_GetTenantTimezone_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepoInterface_GetTenantTimezone_Call) Return(s string, err error) *MockRepoInterface_GetTenantTimezone_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockRepoInterface_GetTenantTimezone_Call) RunAndReturn(run func(ctx context.Context, tenantID uuid.UUID) (string, error)) *MockRepoInterface_GetTenantTimezone_Call {
	_c.Call.Return(run)
	return _c
}

// ListAllStaffBookedSlots provides a mock function for the type MockRepoInterface
func (_mock *MockRepoInterface) ListAllStaffBookedSlots(ctx context.Context, tenantID uuid.UUID, staffIDs []uuid.UUID, from time.Time, to time.Time) (map[uuid.UUID][]appointment.BookedSlot, error) {
	ret := _mock.Called(ctx, tenantID, staffIDs, from, to)

	if len(ret) == 0 {
		panic("no return value specified for ListAllStaffBookedSlots")
	}

	var r0 map[uuid.UUID][]appointment.BookedSlot
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, []uuid.UUID, time.Time, time.Time) (map[uuid.UUID][]appointment.BookedSlot, error)); ok {
		return returnFunc(ctx, tenantID, staffIDs, from, to)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, []uuid.UUID, time.Time, time.Time) map[uuid.UUID][]appointment.BookedSlot); ok {
		r0 = returnFunc(ctx, tenantID, staffIDs, from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[uuid.UUID][]appointment.BookedSlot)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, []uuid.UUID, time.Time, time.Time) error); ok {
		r1 = returnFunc(ctx, tenantID, staffIDs, from, to)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepoInterface_ListAllStaffBookedSlots_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAllStaffBookedSlots'
type MockRepoInterface_ListAllStaffBookedSlots_Call struct {
	*mock.Call
}

// ListAllStaffBookedSlots is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID uuid.UUID
//   - staffIDs []uuid.UUID
//   - from time.Time
//   - to time.Time
func (_e *MockRepoInterface_Expecter) ListAllStaffBookedSlots(ctx interface{}, tenantID interface{}, staffIDs interface{}, from interface{}, to interface{}) *MockRepoInterface_ListAllStaffBookedSlots_Call {
	return &MockRepoInterface_ListAllStaffBookedSlots_Call{Call: _e.mock.On("ListAllStaffBookedSlots", ctx, tenantID, staffIDs, from, to)}
}

func (_c *MockRepoInterface_ListAllStaffBookedSlots_Call) Run(run func(ctx context.Context, tenantID uuid.UUID, staffIDs []uuid.UUID, from time.Time, to time.Time)) *MockRepoInterface_ListAllStaffBookedSlots_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 []uuid.UUID
		if args[2] != nil {
			arg2 = args[2].([]uuid.UUID)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		var arg4 time.Time
		if args[4] != nil {
			arg4 = args[4].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockRepoInterface_ListAllStaffBookedSlots_Call) Return(uUIDToBookedSlots map[uuid.UUID][]appointment.BookedSlot, err error) *MockRepoInterface_ListAllStaffBookedSlots_Call {
	_c.Call.Return(uUIDToBookedSlots, err)
	return _c
}

func (_c *MockRepoInterface_ListAllStaffBookedSlots_Call) RunAndReturn(run func(ctx context.Context, tenantID uuid.UUID, staffIDs []uuid.UUID, from time.Time, to time.Time) (map[uuid.UUID][]appointment.BookedSlot, error)) *MockRepoInterface_ListAllStaffBookedSlots_Call {
	_c.Call.Return(run)
	return _c
}

// ListAllStaffScheduleBreaks provides a mock function for the type MockRepoInterface
func (_mock *MockRepoInterface) ListAllStaffScheduleBreaks(ctx context.Context, tenantID uuid.UUID, staffIDs []uuid.UUID) (map[uuid.UUID][]appointment.ScheduleBreak, error) {
	ret := _mock.Called(ctx, tenantID, staffIDs)

	if len(ret) == 0 {
		panic("no return value specified for ListAllStaffScheduleBreaks")
	}

	var r0 map[uuid.UUID][]appointment.ScheduleBreak
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, []uuid.UUID) (map[uuid.UUID][]appointment.ScheduleBreak, error)); ok {
		return returnFunc(ctx, tenantID, staffIDs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, []uuid.UUID) map[uuid.UUID][]appointment.ScheduleBreak); ok {
		r0 = returnFunc(ctx, tenantID, staffIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[uuid.UUID][]appointment.ScheduleBreak)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, []uuid.UUID) error); ok {
		r1 = returnFunc(ctx, tenantID, staffIDs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepoInterface_ListAllStaffScheduleBreaks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAllStaffScheduleBreaks'
type MockRepoInterface_ListAllStaffScheduleBreaks_Call struct {
	*mock.Call
}

// ListAllStaffScheduleBreaks is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID uuid.UUID
//   - staffIDs []uuid.UUID
func (_e *MockRepoInterface_Expecter) ListAllStaffScheduleBreaks(ctx interface{}, tenantID interface{}, staffIDs interface{}) *MockRepoInterface_ListAllStaffScheduleBreaks_Call {
	return &MockRepoInterface_ListAllStaffScheduleBreaks_Call{Call: _e.mock.On("ListAllStaffScheduleBreaks", ctx, tenantID, staffIDs)}
}

func (_c *MockRepoInterface_ListAllStaffScheduleBreaks_Call) Run(run func(ctx context.Context, tenantID uuid.UUID, staffIDs []uuid.UUID)) *MockRepoInterface_ListAllStaffScheduleBreaks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 []uuid.UUID
		if args[2] != nil {
			arg2 = args[2].([]uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepoInterface_ListAllStaffScheduleBreaks_Call) Return(uUIDToScheduleBreaks map[uuid.UUID][]appointment.ScheduleBreak, err error) *MockRepoInterface_ListAllStaffScheduleBreaks_Call {
	_c.Call.Return(uUIDToScheduleBreaks, err)
	return _c
}

func (_c *MockRepoInterface_ListAllStaffScheduleBreaks_Call) RunAndReturn(run func(ctx context.Context, tenantID uuid.UUID, staffIDs []uuid.UUID) (map[uuid.UUID][]appointment.ScheduleBreak, error)) *MockRepoInterface_ListAllStaffScheduleBreaks_Call {
	_c.Call.Return(run)
	return _c
}

// ListAllStaffScheduleRules provides a mock function for the type MockRepoInterface
func (_mock *MockRepoInterface) ListAllStaffScheduleRules(ctx context.Context, tenantID uuid.UUID, staffIDs []uuid.UUID) (map[uuid.UUID][]appointment.ScheduleRule, error) {
	ret := _mock.Called(ctx, tenantID, staffIDs)

	if len(ret) == 0 {
		panic("no return value specified for ListAllStaffScheduleRules")
	}

	var r0 map[uuid.UUID][]appointment.ScheduleRule
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, []uuid.UUID) (map[uuid.UUID][]appointment.ScheduleRule, error)); ok {
		return returnFunc(ctx, tenantID, staffIDs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, []uuid.UUID) map[uuid.UUID][]appointment.ScheduleRule); ok {
		r0 = returnFunc(ctx, tenantID, staffIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[uuid.UUID][]appointment.ScheduleRule)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, []uuid.UUID) error); ok {
		r1 = returnFunc(ctx, tenantID, staffIDs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepoInterface_ListAllStaffScheduleRules_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAllStaffScheduleRules'
type MockRepoInterface_ListAllStaffScheduleRules_Call struct {
	*mock.Call
}

// ListAllStaffScheduleRules is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID uuid.UUID
//   - staffIDs []uuid.UUID
func (_e *MockRepoInterface_Expecter) ListAllStaffScheduleRules(ctx interface{}, tenantID interface{}, staffIDs interface{}) *MockRepoInterface_ListAllStaffScheduleRules_Call {
	return &MockRepoInterface_ListAllStaffScheduleRules_Call{Call: _e.mock.On("ListAllStaffScheduleRules", ctx, tenantID, staffIDs)}
}

func (_c *MockRepoInterface_ListAllStaffScheduleRules_Call) Run(run func(ctx context.Context, tenantID uuid.UUID, staffIDs []uuid.UUID)) *MockRepoInterface_ListAllStaffScheduleRules_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 []uuid.UUID
		if args[2] != nil {
			arg2 = args[2].([]uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepoInterface_ListAllStaffScheduleRules_Call) Return(uUIDToScheduleRules map[uuid.UUID][]appointment.ScheduleRule, err error) *MockRepoInterface_ListAllStaffScheduleRules_Call {
	_c.Call.Return(uUIDToScheduleRules, err)
	return _c
}

func (_c *MockRepoInterface_ListAllStaffScheduleRules_Call) RunAndReturn(run func(ctx context.Context, tenantID uuid.UUID, staffIDs []uuid.UUID) (map[uuid.UUID][]appointment.ScheduleRule, error)) *MockRepoInterface_ListAllStaffScheduleRules_Call {
	_c.Call.Return(run)
	return _c
}

// ListAllStaffTimeOffs provides a mock function for the type MockRepoInterface
func (_mock *MockRepoInterface) ListAllStaffTimeOffs(ctx context.Context, tenantID uuid.UUID, staffIDs []uuid.UUID, from time.Time, to time.Time) (map[uuid.UUID][]appointment.TimeOff, error) {
	ret := _mock.Called(ctx, tenantID, staffIDs, from, to)

	if len(ret) == 0 {
		panic("no return value specified for ListAllStaffTimeOffs")
	}

	var r0 map[uuid.UUID][]appointment.TimeOff
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, []uuid.UUID, time.Time, time.Time) (map[uuid.UUID][]appointment.TimeOff, error)); ok {
		return returnFunc(ctx, tenantID, staffIDs, from, to)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, []uuid.UUID, time.Time, time.Time) map[uuid.UUID][]appointment.TimeOff); ok {
		r0 = returnFunc(ctx, tenantID, staffIDs, from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[uuid.UUID][]appointment.TimeOff)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, []uuid.UUID, time.Time, time.Time) error); ok {
		r1 = returnFunc(ctx, tenantID, staffIDs, from, to)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepoInterface_ListAllStaffTimeOffs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAllStaffTimeOffs'
type MockRepoInterface_ListAllStaffTimeOffs_Call struct {
	*mock.Call
}

// ListAllStaffTimeOffs is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID uuid.UUID
//   - staffIDs []uuid.UUID
//   - from time.Time
//   - to time.Time
func (_e *MockRepoInterface_Expecter) ListAllStaffTimeOffs(ctx interface{}, tenantID interface{}, staffIDs interface{}, from interface{}, to interface{}) *MockRepoInterface_ListAllStaffTimeOffs_Call {
	return &MockRepoInterface_ListAllStaffTimeOffs_Call{Call: _e.mock.On("ListAllStaffTimeOffs", ctx, tenantID, staffIDs, from, to)}
}

func (_c *MockRepoInterface_ListAllStaffTimeOffs_Call) Run(run func(ctx context.Context, tenantID uuid.UUID, staffIDs []uuid.UUID, from time.Time, to time.Time)) *MockRepoInterface_ListAllStaffTimeOffs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 []uuid.UUID
		if args[2] != nil {
			arg2 = args[2].([]uuid.UUID)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		var arg4 time.Time
		if args[4] != nil {
			arg4 = args[4].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockRepoInterface_ListAllStaffTimeOffs_Call) Return(uUIDToTimeOffs map[uuid.UUID][]appointment.TimeOff, err error) *MockRepoInterface_ListAllStaffTimeOffs_Call {
	_c.Call.Return(uUIDToTimeOffs, err)
	return _c
}

func (_c *MockRepoInterface_ListAllStaffTimeOffs_Call) RunAndReturn(run func(ctx context.Context, tenantID uuid.UUID, staffIDs []uuid.UUID, from time.Time, to time.Time) (map[uuid.UUID][]appointment.TimeOff, error)) *MockRepoInterface_ListAllStaffTimeOffs_Call {
	_c.Call.Return(run)
	return _c
}

// ListAppointmentServices provides a mock function for the type MockRepoInterface
func (_mock *MockRepoInterface) ListAppointmentServices(ctx context.Context, appointmentID uuid.UUID) ([]appointment.AppointmentService, error) {
	ret := _mock.Called(ctx, appointmentID)

	if len(ret) == 0 {
		panic("no return value specified for ListAppointmentServices")
	}

	var r0 []appointment.AppointmentService
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]appointment.AppointmentService, error)); ok {
		return returnFunc(ctx, appointmentID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) []appointment.AppointmentService); ok {
		r0 = returnFunc(ctx, appointmentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]appointment.AppointmentService)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, appointmentID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepoInterface_ListAppointmentServices_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAppointmentServices'
type MockRepoInterface_ListAppointmentServices_Call struct {
	*mock.Call
}

// ListAppointmentServices is a helper method to define mock.On call
//   - ctx context.Context
//   - appointmentID uuid.UUID
func (_e *MockRepoInterface_Expecter) ListAppointmentServices(ctx interface{}, appointmentID interface{}) *MockRepoInterface_ListAppointmentServices_Call {
	return &MockRepoInterface_ListAppointmentServices_Call{Call: _e.mock.On("ListAppointmentServices", ctx, appointmentID)}
}

func (_c *MockRepoInterface_ListAppointmentServices_Call) Run(run func(ctx context.Context, appointmentID uuid.UUID)) *MockRepoInterface_ListAppointmentServices_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepoInterface_ListAppointmentServices_Call) Return(appointmentServices []appointment.AppointmentService, err error) *MockRepoInterface_ListAppointmentServices_Call {
	_c.Call.Return(appointmentServices, err)
	return _c
}

func (_c *MockRepoInterface_ListAppointmentServices_Call) RunAndReturn(run func(ctx context.Context, appointmentID uuid.UUID) ([]appointment.AppointmentService, error)) *MockRepoInterface_ListAppointmentServices_Call {
	_c.Call.Return(run)
	return _c
}

// ListAppointments provides a mock function for the type MockRepoInterface
func (_mock *MockRepoInterface) ListAppointments(ctx context.Context, q appointment.ListQuery) ([]appointment.Appointment, int64, error) {
	ret := _mock.Called(ctx, q)

	if len(ret) == 0 {
		panic("no return value specified for ListAppointments")
	}

	var r0 []appointment.Appointment
	var r1 int64
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, appointment.ListQuery) ([]appointment.Appointment, int64, error)); ok {
		return returnFunc(ctx, q)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, appointment.ListQuery) []appointment.Appointment); ok {
		r0 = returnFunc(ctx, q)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]appointment.Appointment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, appointment.ListQuery) int64); ok {
		r1 = returnFunc(ctx, q)
	} else {
		r1 = ret.Get(1).(int64)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, appointment.ListQuery) error); ok {
		r2 = returnFunc(ctx, q)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockRepoInterface_ListAppointments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAppointments'
type MockRepoInterface_ListAppointments_Call struct {
	*mock.Call
}

// ListAppointments is a helper method to define mock.On call
//   - ctx context.Context
//   - q appointment.ListQuery
func (_e *MockRepoInterface_Expecter) ListAppointments(ctx interface{}, q interface{}) *MockRepoInterface_ListAppointments_Call {
	return &MockRepoInterface_ListAppointments_Call{Call: _e.mock.On("ListAppointments", ctx, q)}
}

func (_c *MockRepoInterface_ListAppointments_Call) Run(run func(ctx context.Context, q appointment.ListQuery)) *MockRepoInterface_ListAppointments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 appointment.ListQuery
		if args[1] != nil {
			arg1 = args[1].(appointment.ListQuery)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepoInterface_ListAppointments_Call) Return(appointments []appointment.Appointment, n int64, err error) *MockRepoInterface_ListAppointments_Call {
	_c.Call.Return(appointments, n, err)
	return _c
}

func (_c *MockRepoInterface_ListAppointments_Call) RunAndReturn(run func(ctx context.Context, q appointment.ListQuery) ([]appointment.Appointment, int64, error)) *MockRepoInterface_ListAppointments_Call {
	_c.Call.Return(run)
	return _c
}

// ListBookedSlots provides a mock function for the type MockRepoInterface
func (_mock *MockRepoInterface) ListBookedSlots(ctx context.Context, tenantID uuid.UUID, staffUserID uuid.UUID, from time.Time, to time.Time) ([]appointment.BookedSlot, error) {
	ret := _mock.Called(ctx, tenantID, staffUserID, from, to)

	if len(ret) == 0 {
		panic("no return value specified for ListBookedSlots")
	}

	var r0 []appointment.BookedSlot
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, time.Time, time.Time) ([]appointment.BookedSlot, error)); ok {
		return returnFunc(ctx, tenantID, staffUserID, from, to)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, time.Time, time.Time) []appointment.BookedSlot); ok {
		r0 = returnFunc(ctx, tenantID, staffUserID, from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]appointment.BookedSlot)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, time.Time, time.Time) error); ok {
		r1 = returnFunc(ctx, tenantID, staffUserID, from, to)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepoInterface_ListBookedSlots_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListBookedSlots'
type MockRepoInterface_ListBookedSlots_Call struct {
	*mock.Call
}

// ListBookedSlots is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID uuid.UUID
//   - staffUserID uuid.UUID
//   - from time.Time
//   - to time.Time
func (_e *MockRepoInterface_Expecter) ListBookedSlots(ctx interface{}, tenantID interface{}, staffUserID interface{}, from interface{}, to interface{}) *MockRepoInterface_ListBookedSlots_Call {
	return &MockRepoInterface_ListBookedSlots_Call{Call: _e.mock.On("ListBookedSlots", ctx, tenantID, staffUserID, from, to)}
}

func (_c *MockRepoInterface_ListBookedSlots_Call) Run(run func(ctx context.Context, tenantID uuid.UUID, staffUserID uuid.UUID, from time.Time, to time.Time)) *MockRepoInterface_ListBookedSlots_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		var arg4 time.Time
		if args[4] != nil {
			arg4 = args[4].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockRepoInterface_ListBookedSlots_Call) Return(bookedSlots []appointment.BookedSlot, err error) *MockRepoInterface_ListBookedSlots_Call {
	_c.Call.Return(bookedSlots, err)
	return _c
}

func (_c *MockRepoInterface_ListBookedSlots_Call) RunAndReturn(run func(ctx context.Context, tenantID uuid.UUID, staffUserID uuid.UUID, from time.Time, to time.Time) ([]appointment.BookedSlot, error)) *MockRepoInterface_ListBookedSlots_Call {
	_c.Call.Return(run)
	return _c
}

// ListConflictingAppointments provides a mock function for the type MockRepoInterface
func (_mock *MockRepoInterface) ListConflictingAppointments(ctx context.Context, tenantID uuid.UUID, staffUserID uuid.UUID, from time.Time, to time.Time) ([]appointment.Appointment, error) {
	ret := _mock.Called(ctx, tenantID, staffUserID, from, to)

	if len(ret) == 0 {
		panic("no return value specified for ListConflictingAppointments")
	}

	var r0 []appointment.Appointment
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, time.Time, time.Time) ([]appointment.Appointment, error)); ok {
		return returnFunc(ctx, tenantID, staffUserID, from, to)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, time.Time, time.Time) []appointment.Appointment); ok {
		r0 = returnFunc(ctx, tenantID, staffUserID, from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]appointment.Appointment)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, time.Time, time.Time) error); ok {
		r1 = returnFunc(ctx, tenantID, staffUserID, from, to)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepoInterface_ListConflictingAppointments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListConflictingAppointments'
type MockRepoInterface_ListConflictingAppointments_Call struct {
	*mock.Call
}

// ListConflictingAppointments is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID uuid.UUID
//   - staffUserID uuid.UUID
//   - from time.Time
//   - to time.Time
func (_e *MockRepoInterface_Expecter) ListConflictingAppointments(ctx interface{}, tenantID interface{}, staffUserID interface{}, from interface{}, to interface{}) *MockRepoInterface_ListConflictingAppointments_Call {
	return &MockRepoInterface_ListConflictingAppointments_Call{Call: _e.mock.On("ListConflictingAppointments", ctx, tenantID, staffUserID, from, to)}
}

func (_c *MockRepoInterface_ListConflictingAppointments_Call) Run(run func(ctx context.Context, tenantID uuid.UUID, staffUserID uuid.UUID, from time.Time, to time.Time)) *MockRepoInterface_ListConflictingAppointments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		var arg4 time.Time
		if args[4] != nil {
			arg4 = args[4].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockRepoInterface_ListConflictingAppointments_Call) Return(appointments []appointment.Appointment, err error) *MockRepoInterface_ListConflictingAppointments_Call {
	_c.Call.Return(appointments, err)
	return _c
}

func (_c *MockRepoInterface_ListConflictingAppointments_Call) RunAndReturn(run func(ctx context.Context, tenantID uuid.UUID, staffUserID uuid.UUID, from time.Time, to time.Time) ([]appointment.Appointment, error)) *MockRepoInterface_ListConflictingAppointments_Call {
	_c.Call.Return(run)
	return _c
}

// ListMultiAppointmentServices provides a mock function for the type MockRepoInterface
func (_mock *MockRepoInterface) ListMultiAppointmentServices(ctx context.Context, appointmentIDs []uuid.UUID) ([]appointment.AppointmentService, error) {
	ret := _mock.Called(ctx, appointmentIDs)

	if len(ret) == 0 {
		panic("no return value specified for ListMultiAppointmentServices")
	}

	var r0 []appointment.AppointmentService
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID) ([]appointment.AppointmentService, error)); ok {
		return returnFunc(ctx, appointmentIDs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID) []appointment.AppointmentService); ok {
		r0 = returnFunc(ctx, appointmentIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]appointment.AppointmentService)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []uuid.UUID) error); ok {
		r1 = returnFunc(ctx, appointmentIDs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepoInterface_ListMultiAppointmentServices_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListMultiAppointmentServices'
type MockRepoInterface_ListMultiAppointmentServices_Call struct {
	*mock.Call
}

// ListMultiAppointmentServices is a helper method to define mock.On call
//   - ctx context.Context
//   - appointmentIDs []uuid.UUID
func (_e *MockRepoInterface_Expecter) ListMultiAppointmentServices(ctx interface{}, appointmentIDs interface{}) *MockRepoInterface_ListMultiAppointmentServices_Call {
	return &MockRepoInterface_ListMultiAppointmentServices_Call{Call: _e.mock.On("ListMultiAppointmentServices", ctx, appointmentIDs)}
}

func (_c *MockRepoInterface_ListMultiAppointmentServices_Call) Run(run func(ctx context.Context, appointmentIDs []uuid.UUID)) *MockRepoInterface_ListMultiAppointmentServices_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []uuid.UUID
		if args[1] != nil {
			arg1 = args[1].([]uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepoInterface_ListMultiAppointmentServices_Call) Return(appointmentServices []appointment.AppointmentService, err error) *MockRepoInterface_ListMultiAppointmentServices_Call {
	_c.Call.Return(appointmentServices, err)
	return _c
}

func (_c *MockRepoInterface_ListMultiAppointmentServices_Call) RunAndReturn(run func(ctx context.Context, appointmentIDs []uuid.UUID) ([]appointment.AppointmentService, error)) *MockRepoInterface_ListMultiAppointmentServices_Call {
	_c.Call.Return(run)
	return _c
}

// ListReviewsByAppointmentIDs provides a mock function for the type MockRepoInterface
func (_mock *MockRepoInterface) ListReviewsByAppointmentIDs(ctx context.Context, appointmentIDs []uuid.UUID) (map[uuid.UUID]*appointment.ReviewInfo, error) {
	ret := _mock.Called(ctx, appointmentIDs)

	if len(ret) == 0 {
		panic("no return value specified for ListReviewsByAppointmentIDs")
	}

	var r0 map[uuid.UUID]*appointment.ReviewInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID) (map[uuid.UUID]*appointment.ReviewInfo, error)); ok {
		return returnFunc(ctx, appointmentIDs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID) map[uuid.UUID]*appointment.ReviewInfo); ok {
		r0 = returnFunc(ctx, appointmentIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[uuid.UUID]*appointment.ReviewInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []uuid.UUID) error); ok {
		r1 = returnFunc(ctx, appointmentIDs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepoInterface_ListReviewsByAppointmentIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListReviewsByAppointmentIDs'
type MockRepoInterface_ListReviewsByAppointmentIDs_Call struct {
	*mock.Call
}

// ListReviewsByAppointmentIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - appointmentIDs []uuid.UUID
func (_e *MockRepoInterface_Expecter) ListReviewsByAppointmentIDs(ctx interface{}, appointmentIDs interface{}) *MockRepoInterface_ListReviewsByAppointmentIDs_Call {
	return &MockRepoInterface_ListReviewsByAppointmentIDs_Call{Call: _e.mock.On("ListReviewsByAppointmentIDs", ctx, appointmentIDs)}
}

func (_c *MockRepoInterface_ListReviewsByAppointmentIDs_Call) Run(run func(ctx context.Context, appointmentIDs []uuid.UUID)) *MockRepoInterface_ListReviewsByAppointmentIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []uuid.UUID
		if args[1] != nil {
			arg1 = args[1].([]uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepoInterface_ListReviewsByAppointmentIDs_Call) Return(uUIDToReviewInfo map[uuid.UUID]*appointment.ReviewInfo, err error) *MockRepoInterface_ListReviewsByAppointmentIDs_Call {
	_c.Call.Return(uUIDToReviewInfo, err)
	return _c
}

func (_c *MockRepoInterface_ListReviewsByAppointmentIDs_Call) RunAndReturn(run func(ctx context.Context, appointmentIDs []uuid.UUID) (map[uuid.UUID]*appointment.ReviewInfo, error)) *MockRepoInterface_ListReviewsByAppointmentIDs_Call {
	_c.Call.Return(run)
	return _c
}

// ListScheduleBreaks provides a mock function for the type MockRepoInterface
func (_mock *MockRepoInterface) ListScheduleBreaks(ctx context.Context, tenantID uuid.UUID, staffUserID uuid.UUID) ([]appointment.ScheduleBreak, error) {
	ret := _mock.Called(ctx, tenantID, staffUserID)

	if len(ret) == 0 {
		panic("no return value specified for ListScheduleBreaks")
	}

	var r0 []appointment.ScheduleBreak
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) ([]appointment.ScheduleBreak, error)); ok {
		return returnFunc(ctx, tenantID, staffUserID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) []appointment.ScheduleBreak); ok {
		r0 = returnFunc(ctx, tenantID, staffUserID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]appointment.ScheduleBreak)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, tenantID, staffUserID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepoInterface_ListScheduleBreaks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListScheduleBreaks'
type MockRepoInterface_ListScheduleBreaks_Call struct {
	*mock.Call
}

// ListScheduleBreaks is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID uuid.UUID
//   - staffUserID uuid.UUID
func (_e *MockRepoInterface_Expecter) ListScheduleBreaks(ctx interface{}, tenantID interface{}, staffUserID interface{}) *MockRepoInterface_ListScheduleBreaks_Call {
	return &MockRepoInterface_ListScheduleBreaks_Call{Call: _e.mock.On("ListScheduleBreaks", ctx, tenantID, staffUserID)}
}

func (_c *MockRepoInterface_ListScheduleBreaks_Call) Run(run func(ctx context.Context, tenantID uuid.UUID, staffUserID uuid.UUID)) *MockRepoInterface_ListScheduleBreaks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepoInterface_ListScheduleBreaks_Call) Return(scheduleBreaks []appointment.ScheduleBreak, err error) *MockRepoInterface_ListScheduleBreaks_Call {
	_c.Call.Return(scheduleBreaks, err)
	return _c
}

func (_c *MockRepoInterface_ListScheduleBreaks_Call) RunAndReturn(run func(ctx context.Context, tenantID uuid.UUID, staffUserID uuid.UUID) ([]appointment.ScheduleBreak, error)) *MockRepoInterface_ListScheduleBreaks_Call {
	_c.Call.Return(run)
	return _c
}

// ListScheduleBreaksByDay provides a mock function for the type MockRepoInterface
func (_mock *MockRepoInterface) ListScheduleBreaksByDay(ctx context.Context, tenantID uuid.UUID, staffUserID uuid.UUID, dayOfWeek int) ([]appointment.ScheduleBreak, error) {
	ret := _mock.Called(ctx, tenantID, staffUserID, dayOfWeek)

	if len(ret) == 0 {
		panic("no return value specified for ListScheduleBreaksByDay")
	}

	var r0 []appointment.ScheduleBreak
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, int) ([]appointment.ScheduleBreak, error)); ok {
		return returnFunc(ctx, tenantID, staffUserID, dayOfWeek)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, int) []appointment.ScheduleBreak); ok {
		r0 = returnFunc(ctx, tenantID, staffUserID, dayOfWeek)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]appointment.ScheduleBreak)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, int) error); ok {
		r1 = returnFunc(ctx, tenantID, staffUserID, dayOfWeek)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepoInterface_ListScheduleBreaksByDay_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListScheduleBreaksByDay'
type MockRepoInterface_ListScheduleBreaksByDay_Call struct {
	*mock.Call
}

// ListScheduleBreaksByDay is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID uuid.UUID
//   - staffUserID uuid.UUID
//   - dayOfWeek int
func (_e *MockRepoInterface_Expecter) ListScheduleBreaksByDay(ctx interface{}, tenantID interface{}, staffUserID interface{}, dayOfWeek interface{}) *MockRepoInterface_ListScheduleBreaksByDay_Call {
	return &MockRepoInterface_ListScheduleBreaksByDay_Call{Call: _e.mock.On("ListScheduleBreaksByDay", ctx, tenantID, staffUserID, dayOfWeek)}
}

func (_c *MockRepoInterface_ListScheduleBreaksByDay_Call) Run(run func(ctx context.Context, tenantID uuid.UUID, staffUserID uuid.UUID, dayOfWeek int)) *MockRepoInterface_ListScheduleBreaksByDay_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockRepoInterface_ListScheduleBreaksByDay_Call) Return(scheduleBreaks []appointment.ScheduleBreak, err error) *MockRepoInterface_ListScheduleBreaksByDay_Call {
	_c.Call.Return(scheduleBreaks, err)
	return _c
}

func (_c *MockRepoInterface_ListScheduleBreaksByDay_Call) RunAndReturn(run func(ctx context.Context, tenantID uuid.UUID, staffUserID uuid.UUID, dayOfWeek int) ([]appointment.ScheduleBreak, error)) *MockRepoInterface_ListScheduleBreaksByDay_Call {
	_c.Call.Return(run)
	return _c
}

// ListStaffByServices provides a mock function for the type MockRepoInterface
func (_mock *MockRepoInterface) ListStaffByServices(ctx context.Context, tenantID uuid.UUID, serviceIDs []uuid.UUID) ([]appointment.StaffMember, error) {
	ret := _mock.Called(ctx, tenantID, serviceIDs)

	if len(ret) == 0 {
		panic("no return value specified for ListStaffByServices")
	}

	var r0 []appointment.StaffMember
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, []uuid.UUID) ([]appointment.StaffMember, error)); ok {
		return returnFunc(ctx, tenantID, serviceIDs)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, []uuid.UUID) []appointment.StaffMember); ok {
		r0 = returnFunc(ctx, tenantID, serviceIDs)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]appointment.StaffMember)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, []uuid.UUID) error); ok {
		r1 = returnFunc(ctx, tenantID, serviceIDs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepoInterface_ListStaffByServices_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListStaffByServices'
type MockRepoInterface_ListStaffByServices_Call struct {
	*mock.Call
}

// ListStaffByServices is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID uuid.UUID
//   - serviceIDs []uuid.UUID
func (_e *MockRepoInterface_Expecter) ListStaffByServices(ctx interface{}, tenantID interface{}, serviceIDs interface{}) *MockRepoInterface_ListStaffByServices_Call {
	return &MockRepoInterface_ListStaffByServices_Call{Call: _e.mock.On("ListStaffByServices", ctx, tenantID, serviceIDs)}
}

func (_c *MockRepoInterface_ListStaffByServices_Call) Run(run func(ctx context.Context, tenantID uuid.UUID, serviceIDs []uuid.UUID)) *MockRepoInterface_ListStaffByServices_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 []uuid.UUID
		if args[2] != nil {
			arg2 = args[2].([]uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepoInterface_ListStaffByServices_Call) Return(staffMembers []appointment.StaffMember, err error) *MockRepoInterface_ListStaffByServices_Call {
	_c.Call.Return(staffMembers, err)
	return _c
}

func (_c *MockRepoInterface_ListStaffByServices_Call) RunAndReturn(run func(ctx context.Context, tenantID uuid.UUID, serviceIDs []uuid.UUID) ([]appointment.StaffMember, error)) *MockRepoInterface_ListStaffByServices_Call {
	_c.Call.Return(run)
	return _c
}

// ListStaffScheduleRules provides a mock function for the type MockRepoInterface
func (_mock *MockRepoInterface) ListStaffScheduleRules(ctx context.Context, tenantID uuid.UUID, staffUserID uuid.UUID) ([]appointment.ScheduleRule, error) {
	ret := _mock.Called(ctx, tenantID, staffUserID)

	if len(ret) == 0 {
		panic("no return value specified for ListStaffScheduleRules")
	}

	var r0 []appointment.ScheduleRule
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) ([]appointment.ScheduleRule, error)); ok {
		return returnFunc(ctx, tenantID, staffUserID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) []appointment.ScheduleRule); ok {
		r0 = returnFunc(ctx, tenantID, staffUserID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]appointment.ScheduleRule)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, tenantID, staffUserID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepoInterface_ListStaffScheduleRules_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListStaffScheduleRules'
type MockRepoInterface_ListStaffScheduleRules_Call struct {
	*mock.Call
}

// ListStaffScheduleRules is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID uuid.UUID
//   - staffUserID uuid.UUID
func (_e *MockRepoInterface_Expecter) ListStaffScheduleRules(ctx interface{}, tenantID interface{}, staffUserID interface{}) *MockRepoInterface_ListStaffScheduleRules_Call {
	return &MockRepoInterface_ListStaffScheduleRules_Call{Call: _e.mock.On("ListStaffScheduleRules", ctx, tenantID, staffUserID)}
}

func (_c *MockRepoInterface_ListStaffScheduleRules_Call) Run(run func(ctx context.Context, tenantID uuid.UUID, staffUserID uuid.UUID)) *MockRepoInterface_ListStaffScheduleRules_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepoInterface_ListStaffScheduleRules_Call) Return(scheduleRules []appointment.ScheduleRule, err error) *MockRepoInterface_ListStaffScheduleRules_Call {
	_c.Call.Return(scheduleRules, err)
	return _c
}

func (_c *MockRepoInterface_ListStaffScheduleRules_Call) RunAndReturn(run func(ctx context.Context, tenantID uuid.UUID, staffUserID uuid.UUID) ([]appointment.ScheduleRule, error)) *MockRepoInterface_ListStaffScheduleRules_Call {
	_c.Call.Return(run)
	return _c
}

// ListStaffServicesByStaff provides a mock function for the type MockRepoInterface
func (_mock *MockRepoInterface) ListStaffServicesByStaff(ctx context.Context, tenantID uuid.UUID, staffUserID uuid.UUID) ([]appointment.ServiceRecord, error) {
	ret := _mock.Called(ctx, tenantID, staffUserID)

	if len(ret) == 0 {
		panic("no return value specified for ListStaffServicesByStaff")
	}

	var r0 []appointment.ServiceRecord
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) ([]appointment.ServiceRecord, error)); ok {
		return returnFunc(ctx, tenantID, staffUserID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) []appointment.ServiceRecord); ok {
		r0 = returnFunc(ctx, tenantID, staffUserID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]appointment.ServiceRecord)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, tenantID, staffUserID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepoInterface_ListStaffServicesByStaff_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListStaffServicesByStaff'
type MockRepoInterface_ListStaffServicesByStaff_Call struct {
	*mock.Call
}

// ListStaffServicesByStaff is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID uuid.UUID
//   - staffUserID uuid.UUID
func (_e *MockRepoInterface_Expecter) ListStaffServicesByStaff(ctx interface{}, tenantID interface{}, staffUserID interface{}) *MockRepoInterface_ListStaffServicesByStaff_Call {
	return &MockRepoInterface_ListStaffServicesByStaff_Call{Call: _e.mock.On("ListStaffServicesByStaff", ctx, tenantID, staffUserID)}
}

func (_c *MockRepoInterface_ListStaffServicesByStaff_Call) Run(run func(ctx context.Context, tenantID uuid.UUID, staffUserID uuid.UUID)) *MockRepoInterface_ListStaffServicesByStaff_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepoInterface_ListStaffServicesByStaff_Call) Return(serviceRecords []appointment.ServiceRecord, err error) *MockRepoInterface_ListStaffServicesByStaff_Call {
	_c.Call.Return(serviceRecords, err)
	return _c
}

func (_c *MockRepoInterface_ListStaffServicesByStaff_Call) RunAndReturn(run func(ctx context.Context, tenantID uuid.UUID, staffUserID uuid.UUID) ([]appointment.ServiceRecord, error)) *MockRepoInterface_ListStaffServicesByStaff_Call {
	_c.Call.Return(run)
	return _c
}

// ListTimeOffs provides a mock function for the type MockRepoInterface
func (_mock *MockRepoInterface) ListTimeOffs(ctx context.Context, tenantID uuid.UUID, staffUserID uuid.UUID, from time.Time, to time.Time) ([]appointment.TimeOff, error) {
	ret := _mock.Called(ctx, tenantID, staffUserID, from, to)

	if len(ret) == 0 {
		panic("no return value specified for ListTimeOffs")
	}

	var r0 []appointment.TimeOff
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, time.Time, time.Time) ([]appointment.TimeOff, error)); ok {
		return returnFunc(ctx, tenantID, staffUserID, from, to)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, time.Time, time.Time) []appointment.TimeOff); ok {
		r0 = returnFunc(ctx, tenantID, staffUserID, from, to)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]appointment.TimeOff)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, time.Time, time.Time) error); ok {
		r1 = returnFunc(ctx, tenantID, staffUserID, from, to)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepoInterface_ListTimeOffs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTimeOffs'
type MockRepoInterface_ListTimeOffs_Call struct {
	*mock.Call
}

// ListTimeOffs is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID uuid.UUID
//   - staffUserID uuid.UUID
//   - from time.Time
//   - to time.Time
func (_e *MockRepoInterface_Expecter) ListTimeOffs(ctx interface{}, tenantID interface{}, staffUserID interface{}, from interface{}, to interface{}) *MockRepoInterface_ListTimeOffs_Call {
	return &MockRepoInterface_ListTimeOffs_Call{Call: _e.mock.On("ListTimeOffs", ctx, tenantID, staffUserID, from, to)}
}

func (_c *MockRepoInterface_ListTimeOffs_Call) Run(run func(ctx context.Context, tenantID uuid.UUID, staffUserID uuid.UUID, from time.Time, to time.Time)) *MockRepoInterface_ListTimeOffs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 time.Time
		if args[3] != nil {
			arg3 = args[3].(time.Time)
		}
		var arg4 time.Time
		if args[4] != nil {
			arg4 = args[4].(time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockRepoInterface_ListTimeOffs_Call) Return(timeOffs []appointment.TimeOff, err error) *MockRepoInterface_ListTimeOffs_Call {
	_c.Call.Return(timeOffs, err)
	return _c
}

func (_c *MockRepoInterface_ListTimeOffs_Call) RunAndReturn(run func(ctx context.Context, tenantID uuid.UUID, staffUserID uuid.UUID, from time.Time, to time.Time) ([]appointment.TimeOff, error)) *MockRepoInterface_ListTimeOffs_Call {
	_c.Call.Return(run)
	return _c
}

// RunInTx provides a mock function for the type MockRepoInterface
func (_mock *MockRepoInterface) RunInTx(ctx context.Context, fn func(ctx context.Context) error) error {
	ret := _mock.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for RunInTx")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, func(ctx context.Context) error) error); ok {
		r0 = returnFunc(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepoInterface_RunInTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunInTx'
type MockRepoInterface_RunInTx_Call struct {
	*mock.Call
}

// RunInTx is a helper method to define mock.On call
//   - ctx context.Context
//   - fn func(ctx context.Context) error
func (_e *MockRepoInterface_Expecter) RunInTx(ctx interface{}, fn interface{}) *MockRepoInterface_RunInTx_Call {
	return &MockRepoInterface_RunInTx_Call{Call: _e.mock.On("RunInTx", ctx, fn)}
}

func (_c *MockRepoInterface_RunInTx_Call) Run(run func(ctx context.Context, fn func(ctx context.Context) error)) *MockRepoInterface_RunInTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 func(ctx context.Context) error
		if args[1] != nil {
			arg1 = args[1].(func(ctx context.Context) error)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepoInterface_RunInTx_Call) Return(err error) *MockRepoInterface_RunInTx_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepoInterface_RunInTx_Call) RunAndReturn(run func(ctx context.Context, fn func(ctx context.Context) error) error) *MockRepoInterface_RunInTx_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateAppointmentStatus provides a mock function for the type MockRepoInterface
func (_mock *MockRepoInterface) UpdateAppointmentStatus(ctx context.Context, tenantID uuid.UUID, appointmentID uuid.UUID, status string, extra map[string]interface{}) error {
	ret := _mock.Called(ctx, tenantID, appointmentID, status, extra)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAppointmentStatus")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string, map[string]interface{}) error); ok {
		r0 = returnFunc(ctx, tenantID, appointmentID, status, extra)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepoInterface_UpdateAppointmentStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateAppointmentStatus'
type MockRepoInterface_UpdateAppointmentStatus_Call struct {
	*mock.Call
}

// UpdateAppointmentStatus is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID uuid.UUID
//   - appointmentID uuid.UUID
//   - status string
//   - extra map[string]interface{}
func (_e *MockRepoInterface_Expecter) UpdateAppointmentStatus(ctx interface{}, tenantID interface{}, appointmentID interface{}, status interface{}, extra interface{}) *MockRepoInterface_UpdateAppointmentStatus_Call {
	return &MockRepoInterface_UpdateAppointmentStatus_Call{Call: _e.mock.On("UpdateAppointmentStatus", ctx, tenantID, appointmentID, status, extra)}
}

func (_c *MockRepoInterface_UpdateAppointmentStatus_Call) Run(run func(ctx context.Context, tenantID uuid.UUID, appointmentID uuid.UUID, status string, extra map[string]interface{})) *MockRepoInterface_UpdateAppointmentStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 map[string]interface{}
		if args[4] != nil {
			arg4 = args[4].(map[string]interface{})
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockRepoInterface_UpdateAppointmentStatus_Call) Return(err error) *MockRepoInterface_UpdateAppointmentStatus_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepoInterface_UpdateAppointmentStatus_Call) RunAndReturn(run func(ctx context.Context, tenantID uuid.UUID, appointmentID uuid.UUID, status string, extra map[string]interface{}) error) *MockRepoInterface_UpdateAppointmentStatus_Call {
	_c.Call.Return(run)
	return _c
}
