// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockLoyaltyService creates a new instance of MockLoyaltyService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockLoyaltyService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockLoyaltyService {
	mock := &MockLoyaltyService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockLoyaltyService is an autogenerated mock type for the LoyaltyService type
type MockLoyaltyService struct {
	mock.Mock
}

type MockLoyaltyService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockLoyaltyService) EXPECT() *MockLoyaltyService_Expecter {
	return &MockLoyaltyService_Expecter{mock: &_m.Mock}
}

// AwardPoints provides a mock function for the type MockLoyaltyService
func (_mock *MockLoyaltyService) AwardPoints(ctx context.Context, tenantID uuid.UUID, customerID uuid.UUID, appointmentID uuid.UUID, pointsReward int) error {
	ret := _mock.Called(ctx, tenantID, customerID, appointmentID, pointsReward)

	if len(ret) == 0 {
		panic("no return value specified for AwardPoints")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID, int) error); ok {
		r0 = returnFunc(ctx, tenantID, customerID, appointmentID, pointsReward)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockLoyaltyService_AwardPoints_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AwardPoints'
type MockLoyaltyService_AwardPoints_Call struct {
	*mock.Call
}

// AwardPoints is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID uuid.UUID
//   - customerID uuid.UUID
//   - appointmentID uuid.UUID
//   - pointsReward int
func (_e *MockLoyaltyService_Expecter) AwardPoints(ctx interface{}, tenantID interface{}, customerID interface{}, appointmentID interface{}, pointsReward interface{}) *MockLoyaltyService_AwardPoints_Call {
	return &MockLoyaltyService_AwardPoints_Call{Call: _e.mock.On("AwardPoints", ctx, tenantID, customerID, appointmentID, pointsReward)}
}

func (_c *MockLoyaltyService_AwardPoints_Call) Run(run func(ctx context.Context, tenantID uuid.UUID, customerID uuid.UUID, appointmentID uuid.UUID, pointsReward int)) *MockLoyaltyService_AwardPoints_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 uuid.UUID
		if args[3] != nil {
			arg3 = args[3].(uuid.UUID)
		}
		var arg4 int
		if args[4] != nil {
			arg4 = args[4].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockLoyaltyService_AwardPoints_Call) Return(err error) *MockLoyaltyService_AwardPoints_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockLoyaltyService_AwardPoints_Call) RunAndReturn(run func(ctx context.Context, tenantID uuid.UUID, customerID uuid.UUID, appointmentID uuid.UUID, pointsReward int) error) *MockLoyaltyService_AwardPoints_Call {
	_c.Call.Return(run)
	return _c
}
